#
# Makefile for BCM97630 board
#
# Copyright (C) 2009 Broadcom Corporation
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed with the hope that it will be useful, but without
# any warranty; without even the implied warranty of merchantability or
# fitness for a particular purpose.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
#
#
# Makefile for BCM97630 board
#
# when     who what
# -------- --- ------------------------------------------------------



obj-y	 += irq.o bcm_uart.o hw_init.o board.o bcm97630.o

obj-$(CONFIG_NDVD_PWR_MGMT) += power_seq.o

#obj-m += hwdebug.o


