/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_ddr23_phy_control_regs_1.h $
 * $brcm_Revision: Hydra_Software_Devel/2 $
 * $brcm_Date: 9/2/09 12:42a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Sep  1 17:44:24 2009
 *                 MD5 Checksum         899cfa957dec7d063f95a3caedf94791
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7635/rdb/a0/bchp_ddr23_phy_control_regs_1.h $
 * 
 * Hydra_Software_Devel/2   9/2/09 12:42a tdo
 * SW7635-44: Regenerate header files
 *
 ***************************************************************************/

#ifndef BCHP_DDR23_PHY_CONTROL_REGS_1_H__
#define BCHP_DDR23_PHY_CONTROL_REGS_1_H__

/***************************************************************************
 *DDR23_PHY_CONTROL_REGS_1 - DDR23 DDR23 physical interface control registers 1
 ***************************************************************************/
#define BCHP_DDR23_PHY_CONTROL_REGS_1_REVISION   0x01806000 /* Address & Control revision register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_CLK_PM_CTRL 0x01806004 /* PHY clock power management control register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_PLL_STATUS 0x01806010 /* PHY PLL status register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_PLL_CONFIG 0x01806014 /* PHY PLL configuration register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_PLL_PRE_DIVIDER 0x01806018 /* PHY PLL pre-divider control register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_PLL_DIVIDER 0x0180601c /* PHY PLL divider control register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_PLL_CONTROL1 0x01806020 /* PHY PLL analog control register #1 */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_PLL_CONTROL2 0x01806024 /* PHY PLL analog control register #2 */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_PLL_SS_EN  0x01806028 /* PHY PLL spread spectrum config register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_PLL_SS_CFG 0x0180602c /* PHY PLL spread spectrum config register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_STATIC_VDL_OVERRIDE 0x01806030 /* Address & Control VDL static override control register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_DYNAMIC_VDL_OVERRIDE 0x01806034 /* Address & Control VDL dynamic override control register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_IDLE_PAD_CONTROL 0x01806038 /* Idle mode SSTL pad control register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_ZQ_PVT_COMP_CTL 0x0180603c /* PVT Compensation control and status register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_DRIVE_PAD_CTL 0x01806040 /* SSTL pad drive characteristics control register */
#define BCHP_DDR23_PHY_CONTROL_REGS_1_CLOCK_REG_CONTROL 0x01806044 /* Clock Regulator control register */

#endif /* #ifndef BCHP_DDR23_PHY_CONTROL_REGS_1_H__ */

/* End of File */
