/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_sata_ide_1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 12/2/08 7:26p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Dec  2 14:03:59 2008
 *                 MD5 Checksum         90975bbcdf76045bb6bd092e6bdf481b
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7635/rdb/a0/bchp_sata_ide_1.h $
 * 
 * Hydra_Software_Devel/1   12/2/08 7:26p albertl
 * PR48688: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_SATA_IDE_1_H__
#define BCHP_SATA_IDE_1_H__

/***************************************************************************
 *SATA_IDE_1 - Primary IDE Register Space 1
 ***************************************************************************/
#define BCHP_SATA_IDE_1_IDE_COMMAND              0x5a0200 /* Bus-master IDE Command Register */
#define BCHP_SATA_IDE_1_IDE_STATUS               0x5a0201 /* Bus-master IDE Status Register */
#define BCHP_SATA_IDE_1_DES_TABLE                0x005a0204 /* Descriptor Table Pointer & Transfer Address Register */

#endif /* #ifndef BCHP_SATA_IDE_1_H__ */

/* End of File */
