/***************************************************************************
 *     Copyright (c) 1999-2008, Broadcom Corporation
 *     All Rights Reserved
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_ofe_datapath_intr2.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 12/2/08 6:59p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Dec  2 14:02:08 2008
 *                 MD5 Checksum         90975bbcdf76045bb6bd092e6bdf481b
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7635/rdb/a0/bchp_ofe_datapath_intr2.h $
 * 
 * Hydra_Software_Devel/1   12/2/08 6:59p albertl
 * PR48688: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_OFE_DATAPATH_INTR2_H__
#define BCHP_OFE_DATAPATH_INTR2_H__

/***************************************************************************
 *OFE_DATAPATH_INTR2 - OFE Datapath Level 2 Interrupt Controller
 ***************************************************************************/
#define BCHP_OFE_DATAPATH_INTR2_CPU_STATUS       0x002a0000 /* CPU interrupt Status Register */
#define BCHP_OFE_DATAPATH_INTR2_CPU_SET          0x002a0004 /* CPU interrupt Set Register */
#define BCHP_OFE_DATAPATH_INTR2_CPU_CLEAR        0x002a0008 /* CPU interrupt Clear Register */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_STATUS  0x002a000c /* CPU interrupt Mask Status Register */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_SET     0x002a0010 /* CPU interrupt Mask Set Register */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_CLEAR   0x002a0014 /* CPU interrupt Mask Clear Register */
#define BCHP_OFE_DATAPATH_INTR2_PCI_STATUS       0x002a0018 /* PCI interrupt Status Register */
#define BCHP_OFE_DATAPATH_INTR2_PCI_SET          0x002a001c /* PCI interrupt Set Register */
#define BCHP_OFE_DATAPATH_INTR2_PCI_CLEAR        0x002a0020 /* PCI interrupt Clear Register */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_STATUS  0x002a0024 /* PCI interrupt Mask Status Register */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_SET     0x002a0028 /* PCI interrupt Mask Set Register */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_CLEAR   0x002a002c /* PCI interrupt Mask Clear Register */

/***************************************************************************
 *CPU_STATUS - CPU interrupt Status Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: CPU_STATUS :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_STATUS_reserved0_MASK          0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_CPU_STATUS_reserved0_SHIFT         2

/* OFE_DATAPATH_INTR2 :: CPU_STATUS :: GR_BRIDGE_ERROR [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_STATUS_GR_BRIDGE_ERROR_MASK    0x00000002
#define BCHP_OFE_DATAPATH_INTR2_CPU_STATUS_GR_BRIDGE_ERROR_SHIFT   1

/* OFE_DATAPATH_INTR2 :: CPU_STATUS :: MIPS_MAILBOX [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_STATUS_MIPS_MAILBOX_MASK       0x00000001
#define BCHP_OFE_DATAPATH_INTR2_CPU_STATUS_MIPS_MAILBOX_SHIFT      0

/***************************************************************************
 *CPU_SET - CPU interrupt Set Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: CPU_SET :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_SET_reserved0_MASK             0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_CPU_SET_reserved0_SHIFT            2

/* OFE_DATAPATH_INTR2 :: CPU_SET :: GR_BRIDGE_ERROR [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_SET_GR_BRIDGE_ERROR_MASK       0x00000002
#define BCHP_OFE_DATAPATH_INTR2_CPU_SET_GR_BRIDGE_ERROR_SHIFT      1

/* OFE_DATAPATH_INTR2 :: CPU_SET :: MIPS_MAILBOX [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_SET_MIPS_MAILBOX_MASK          0x00000001
#define BCHP_OFE_DATAPATH_INTR2_CPU_SET_MIPS_MAILBOX_SHIFT         0

/***************************************************************************
 *CPU_CLEAR - CPU interrupt Clear Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: CPU_CLEAR :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_CLEAR_reserved0_MASK           0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_CPU_CLEAR_reserved0_SHIFT          2

/* OFE_DATAPATH_INTR2 :: CPU_CLEAR :: GR_BRIDGE_ERROR [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_CLEAR_GR_BRIDGE_ERROR_MASK     0x00000002
#define BCHP_OFE_DATAPATH_INTR2_CPU_CLEAR_GR_BRIDGE_ERROR_SHIFT    1

/* OFE_DATAPATH_INTR2 :: CPU_CLEAR :: MIPS_MAILBOX [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_CLEAR_MIPS_MAILBOX_MASK        0x00000001
#define BCHP_OFE_DATAPATH_INTR2_CPU_CLEAR_MIPS_MAILBOX_SHIFT       0

/***************************************************************************
 *CPU_MASK_STATUS - CPU interrupt Mask Status Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: CPU_MASK_STATUS :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_STATUS_reserved0_MASK     0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_STATUS_reserved0_SHIFT    2

/* OFE_DATAPATH_INTR2 :: CPU_MASK_STATUS :: GR_BRIDGE_ERROR_MASK [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_STATUS_GR_BRIDGE_ERROR_MASK_MASK 0x00000002
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_STATUS_GR_BRIDGE_ERROR_MASK_SHIFT 1

/* OFE_DATAPATH_INTR2 :: CPU_MASK_STATUS :: MIPS_MAILBOX_MASK [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_STATUS_MIPS_MAILBOX_MASK_MASK 0x00000001
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_STATUS_MIPS_MAILBOX_MASK_SHIFT 0

/***************************************************************************
 *CPU_MASK_SET - CPU interrupt Mask Set Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: CPU_MASK_SET :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_SET_reserved0_MASK        0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_SET_reserved0_SHIFT       2

/* OFE_DATAPATH_INTR2 :: CPU_MASK_SET :: GR_BRIDGE_ERROR_MASK [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_SET_GR_BRIDGE_ERROR_MASK_MASK 0x00000002
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_SET_GR_BRIDGE_ERROR_MASK_SHIFT 1

/* OFE_DATAPATH_INTR2 :: CPU_MASK_SET :: MIPS_MAILBOX_MASK [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_SET_MIPS_MAILBOX_MASK_MASK 0x00000001
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_SET_MIPS_MAILBOX_MASK_SHIFT 0

/***************************************************************************
 *CPU_MASK_CLEAR - CPU interrupt Mask Clear Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: CPU_MASK_CLEAR :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_CLEAR_reserved0_MASK      0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_CLEAR_reserved0_SHIFT     2

/* OFE_DATAPATH_INTR2 :: CPU_MASK_CLEAR :: GR_BRIDGE_ERROR_MASK [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_CLEAR_GR_BRIDGE_ERROR_MASK_MASK 0x00000002
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_CLEAR_GR_BRIDGE_ERROR_MASK_SHIFT 1

/* OFE_DATAPATH_INTR2 :: CPU_MASK_CLEAR :: MIPS_MAILBOX_MASK [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_CLEAR_MIPS_MAILBOX_MASK_MASK 0x00000001
#define BCHP_OFE_DATAPATH_INTR2_CPU_MASK_CLEAR_MIPS_MAILBOX_MASK_SHIFT 0

/***************************************************************************
 *PCI_STATUS - PCI interrupt Status Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: PCI_STATUS :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_STATUS_reserved0_MASK          0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_PCI_STATUS_reserved0_SHIFT         2

/* OFE_DATAPATH_INTR2 :: PCI_STATUS :: GR_BRIDGE_ERROR [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_STATUS_GR_BRIDGE_ERROR_MASK    0x00000002
#define BCHP_OFE_DATAPATH_INTR2_PCI_STATUS_GR_BRIDGE_ERROR_SHIFT   1

/* OFE_DATAPATH_INTR2 :: PCI_STATUS :: MIPS_MAILBOX [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_STATUS_MIPS_MAILBOX_MASK       0x00000001
#define BCHP_OFE_DATAPATH_INTR2_PCI_STATUS_MIPS_MAILBOX_SHIFT      0

/***************************************************************************
 *PCI_SET - PCI interrupt Set Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: PCI_SET :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_SET_reserved0_MASK             0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_PCI_SET_reserved0_SHIFT            2

/* OFE_DATAPATH_INTR2 :: PCI_SET :: GR_BRIDGE_ERROR [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_SET_GR_BRIDGE_ERROR_MASK       0x00000002
#define BCHP_OFE_DATAPATH_INTR2_PCI_SET_GR_BRIDGE_ERROR_SHIFT      1

/* OFE_DATAPATH_INTR2 :: PCI_SET :: MIPS_MAILBOX [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_SET_MIPS_MAILBOX_MASK          0x00000001
#define BCHP_OFE_DATAPATH_INTR2_PCI_SET_MIPS_MAILBOX_SHIFT         0

/***************************************************************************
 *PCI_CLEAR - PCI interrupt Clear Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: PCI_CLEAR :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_CLEAR_reserved0_MASK           0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_PCI_CLEAR_reserved0_SHIFT          2

/* OFE_DATAPATH_INTR2 :: PCI_CLEAR :: GR_BRIDGE_ERROR [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_CLEAR_GR_BRIDGE_ERROR_MASK     0x00000002
#define BCHP_OFE_DATAPATH_INTR2_PCI_CLEAR_GR_BRIDGE_ERROR_SHIFT    1

/* OFE_DATAPATH_INTR2 :: PCI_CLEAR :: MIPS_MAILBOX [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_CLEAR_MIPS_MAILBOX_MASK        0x00000001
#define BCHP_OFE_DATAPATH_INTR2_PCI_CLEAR_MIPS_MAILBOX_SHIFT       0

/***************************************************************************
 *PCI_MASK_STATUS - PCI interrupt Mask Status Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: PCI_MASK_STATUS :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_STATUS_reserved0_MASK     0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_STATUS_reserved0_SHIFT    2

/* OFE_DATAPATH_INTR2 :: PCI_MASK_STATUS :: GR_BRIDGE_ERROR_MASK [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_STATUS_GR_BRIDGE_ERROR_MASK_MASK 0x00000002
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_STATUS_GR_BRIDGE_ERROR_MASK_SHIFT 1

/* OFE_DATAPATH_INTR2 :: PCI_MASK_STATUS :: MIPS_MAILBOX_MASK [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_STATUS_MIPS_MAILBOX_MASK_MASK 0x00000001
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_STATUS_MIPS_MAILBOX_MASK_SHIFT 0

/***************************************************************************
 *PCI_MASK_SET - PCI interrupt Mask Set Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: PCI_MASK_SET :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_SET_reserved0_MASK        0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_SET_reserved0_SHIFT       2

/* OFE_DATAPATH_INTR2 :: PCI_MASK_SET :: GR_BRIDGE_ERROR_MASK [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_SET_GR_BRIDGE_ERROR_MASK_MASK 0x00000002
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_SET_GR_BRIDGE_ERROR_MASK_SHIFT 1

/* OFE_DATAPATH_INTR2 :: PCI_MASK_SET :: MIPS_MAILBOX_MASK [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_SET_MIPS_MAILBOX_MASK_MASK 0x00000001
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_SET_MIPS_MAILBOX_MASK_SHIFT 0

/***************************************************************************
 *PCI_MASK_CLEAR - PCI interrupt Mask Clear Register
 ***************************************************************************/
/* OFE_DATAPATH_INTR2 :: PCI_MASK_CLEAR :: reserved0 [31:02] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_CLEAR_reserved0_MASK      0xfffffffc
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_CLEAR_reserved0_SHIFT     2

/* OFE_DATAPATH_INTR2 :: PCI_MASK_CLEAR :: GR_BRIDGE_ERROR_MASK [01:01] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_CLEAR_GR_BRIDGE_ERROR_MASK_MASK 0x00000002
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_CLEAR_GR_BRIDGE_ERROR_MASK_SHIFT 1

/* OFE_DATAPATH_INTR2 :: PCI_MASK_CLEAR :: MIPS_MAILBOX_MASK [00:00] */
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_CLEAR_MIPS_MAILBOX_MASK_MASK 0x00000001
#define BCHP_OFE_DATAPATH_INTR2_PCI_MASK_CLEAR_MIPS_MAILBOX_MASK_SHIFT 0

#endif /* #ifndef BCHP_OFE_DATAPATH_INTR2_H__ */

/* End of File */
