/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_ofe_armcr4_bridge.h $
 * $brcm_Revision: Hydra_Software_Devel/2 $
 * $brcm_Date: 3/20/09 5:14p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 16:06:41 2009
 *                 MD5 Checksum         d2113c6e4c1720eae253e3fd9af4b5f2
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7635/rdb/a0/bchp_ofe_armcr4_bridge.h $
 * 
 * Hydra_Software_Devel/2   3/20/09 5:14p albertl
 * PR52957: Updated to match RDB.
 *
 ***************************************************************************/

#ifndef BCHP_OFE_ARMCR4_BRIDGE_H__
#define BCHP_OFE_ARMCR4_BRIDGE_H__

/***************************************************************************
 *OFE_ARMCR4_BRIDGE - ARM Cortex R4 Bridge control registers
 ***************************************************************************/
#define BCHP_OFE_ARMCR4_BRIDGE_REG_CORE_REV_ID   0x00280000 /* ARM Cortex R4 bridge revision ID */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL    0x00280004 /* Bridge interface and buffer configuration */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL       0x00280008 /* ARM core configuration */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_OFFSET   0x0028000c /* ARM/OFE DRAM space offset */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_RANGE    0x00280010 /* ARM/OFE DRAM range */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS    0x00280014 /* Bridge interface and buffer status */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_MIPS     0x00280018 /* MIPS mailbox #1 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_ARM      0x0028001c /* ARM mailbox #1 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_ARM_CLEAR 0x00280020 /* ARM mailbox #1 clear */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_1   0x00280024 /* CPU semaphore #1 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_2   0x00280028 /* CPU semaphore #2 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_3   0x0028002c /* CPU semaphore #3 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_4   0x00280030 /* CPU semaphore #4 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_1     0x00280034 /* CPU scratchpad #1 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_2     0x00280038 /* CPU scratchpad #2 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_3     0x0028003c /* CPU scratchpad #3 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_4     0x00280040 /* CPU scratchpad #4 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_5     0x00280044 /* CPU scratchpad #5 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_6     0x00280048 /* CPU scratchpad #6 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_7     0x0028004c /* CPU scratchpad #7 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_8     0x00280050 /* CPU scratchpad #8 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_9     0x00280054 /* CPU scratchpad #9 */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_CONFIG   0x00280058 /* Performance monitor configuration */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_LIMIT    0x0028005c /* Performance monitor count threshold */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_WR_CNT   0x00280060 /* Counts the number of merge buffer updates (hits + misses) */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_WR_MISS  0x00280064 /* Counts the number of merge buffer misses */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_RD_CNT   0x00280068 /* Counts the number of prefetch buffer accesses (hits + misses) */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_RD_MISS  0x0028006c /* Counts the number of prefetch buffer misses */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1    0x00280070 /* ARM memory TM1 control register */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2    0x00280074 /* ARM memory TM2 control register */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_HALT      0x00280078 /* ARM halt register - keeps the processor from fetching instructions after reset */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_FIFO_STATUS   0x0028007c /* Fifo Status */

/***************************************************************************
 *REG_CORE_REV_ID - ARM Cortex R4 bridge revision ID
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_CORE_REV_ID :: reserved0 [31:16] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_CORE_REV_ID_reserved0_MASK      0xffff0000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_CORE_REV_ID_reserved0_SHIFT     16

/* OFE_ARMCR4_BRIDGE :: REG_CORE_REV_ID :: MAJOR [15:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_CORE_REV_ID_MAJOR_MASK          0x0000ff00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_CORE_REV_ID_MAJOR_SHIFT         8

/* OFE_ARMCR4_BRIDGE :: REG_CORE_REV_ID :: MINOR [07:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_CORE_REV_ID_MINOR_MASK          0x000000ff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_CORE_REV_ID_MINOR_SHIFT         0

/***************************************************************************
 *REG_BRIDGE_CTL - Bridge interface and buffer configuration
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: reserved0 [31:24] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_reserved0_MASK       0xff000000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_reserved0_SHIFT      24

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: timeout [23:12] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_timeout_MASK         0x00fff000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_timeout_SHIFT        12

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: reserved1 [11:09] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_reserved1_MASK       0x00000e00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_reserved1_SHIFT      9

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: ccb_space_alias_en [08:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_ccb_space_alias_en_MASK 0x00000100
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_ccb_space_alias_en_SHIFT 8

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: timeout_en [07:07] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_timeout_en_MASK      0x00000080
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_timeout_en_SHIFT     7

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: io_sync_en [06:06] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_io_sync_en_MASK      0x00000040
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_io_sync_en_SHIFT     6

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: prefetch_en [05:05] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_prefetch_en_MASK     0x00000020
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_prefetch_en_SHIFT    5

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: gather_en [04:04] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_gather_en_MASK       0x00000010
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_gather_en_SHIFT      4

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: reserved2 [03:02] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_reserved2_MASK       0x0000000c
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_reserved2_SHIFT      2

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: arm_soft_rst [01:01] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_arm_soft_rst_MASK    0x00000002
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_arm_soft_rst_SHIFT   1

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_CTL :: ofe_soft_rst [00:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_ofe_soft_rst_MASK    0x00000001
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_CTL_ofe_soft_rst_SHIFT   0

/***************************************************************************
 *REG_ARM_CTL - ARM core configuration
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: reserved0 [31:09] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_reserved0_MASK          0xfffffe00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_reserved0_SHIFT         9

/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: DAP_DBGEN [08:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_DAP_DBGEN_MASK          0x00000100
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_DAP_DBGEN_SHIFT         8

/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: CR4_DBGEN [07:07] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_CR4_DBGEN_MASK          0x00000080
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_CR4_DBGEN_SHIFT         7

/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: LOCZRAMA [06:06] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_LOCZRAMA_MASK           0x00000040
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_LOCZRAMA_SHIFT          6

/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: RMWENRAM [05:05] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_RMWENRAM_MASK           0x00000020
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_RMWENRAM_SHIFT          5

/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: CFGNMFI [04:04] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_CFGNMFI_MASK            0x00000010
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_CFGNMFI_SHIFT           4

/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: TEINIT [03:03] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_TEINIT_MASK             0x00000008
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_TEINIT_SHIFT            3

/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: CFGEE [02:02] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_CFGEE_MASK              0x00000004
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_CFGEE_SHIFT             2

/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: VINITHI [01:01] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_VINITHI_MASK            0x00000002
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_VINITHI_SHIFT           1

/* OFE_ARMCR4_BRIDGE :: REG_ARM_CTL :: INITRAMA [00:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_INITRAMA_MASK           0x00000001
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_CTL_INITRAMA_SHIFT          0

/***************************************************************************
 *REG_DRAM_OFFSET - ARM/OFE DRAM space offset
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_DRAM_OFFSET :: OFFSET [31:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_OFFSET_OFFSET_MASK         0xffffff00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_OFFSET_OFFSET_SHIFT        8

/* OFE_ARMCR4_BRIDGE :: REG_DRAM_OFFSET :: reserved0 [07:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_OFFSET_reserved0_MASK      0x000000ff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_OFFSET_reserved0_SHIFT     0

/***************************************************************************
 *REG_DRAM_RANGE - ARM/OFE DRAM range
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_DRAM_RANGE :: RANGE [31:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_RANGE_RANGE_MASK           0xffffff00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_RANGE_RANGE_SHIFT          8

/* OFE_ARMCR4_BRIDGE :: REG_DRAM_RANGE :: reserved0 [07:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_RANGE_reserved0_MASK       0x000000ff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_DRAM_RANGE_reserved0_SHIFT      0

/***************************************************************************
 *REG_BRIDGE_STS - Bridge interface and buffer status
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_STS :: reserved0 [31:06] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_reserved0_MASK       0xffffffc0
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_reserved0_SHIFT      6

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_STS :: OFE_RESET_DONE [05:05] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_OFE_RESET_DONE_MASK  0x00000020
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_OFE_RESET_DONE_SHIFT 5

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_STS :: ARM_STANDBYWFI [04:04] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_ARM_STANDBYWFI_MASK  0x00000010
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_ARM_STANDBYWFI_SHIFT 4

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_STS :: prefetch_buff_idle [03:03] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_prefetch_buff_idle_MASK 0x00000008
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_prefetch_buff_idle_SHIFT 3

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_STS :: prefetch_buff_valid [02:02] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_prefetch_buff_valid_MASK 0x00000004
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_prefetch_buff_valid_SHIFT 2

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_STS :: merge_buff_idle [01:01] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_merge_buff_idle_MASK 0x00000002
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_merge_buff_idle_SHIFT 1

/* OFE_ARMCR4_BRIDGE :: REG_BRIDGE_STS :: merge_buff_valid [00:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_merge_buff_valid_MASK 0x00000001
#define BCHP_OFE_ARMCR4_BRIDGE_REG_BRIDGE_STS_merge_buff_valid_SHIFT 0

/***************************************************************************
 *REG_MBOX_MIPS - MIPS mailbox #1
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_MBOX_MIPS :: mbox [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_MIPS_mbox_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_MIPS_mbox_SHIFT            0

/***************************************************************************
 *REG_MBOX_ARM - ARM mailbox #1
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_MBOX_ARM :: mbox [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_ARM_mbox_MASK              0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_ARM_mbox_SHIFT             0

/***************************************************************************
 *REG_MBOX_ARM_CLEAR - ARM mailbox #1 clear
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_MBOX_ARM_CLEAR :: reserved0 [31:01] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_ARM_CLEAR_reserved0_MASK   0xfffffffe
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_ARM_CLEAR_reserved0_SHIFT  1

/* OFE_ARMCR4_BRIDGE :: REG_MBOX_ARM_CLEAR :: mbox_clear [00:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_ARM_CLEAR_mbox_clear_MASK  0x00000001
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MBOX_ARM_CLEAR_mbox_clear_SHIFT 0

/***************************************************************************
 *REG_SEMAPHORE_1 - CPU semaphore #1
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SEMAPHORE_1 :: reserved0 [31:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_1_reserved0_MASK      0xffffff00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_1_reserved0_SHIFT     8

/* OFE_ARMCR4_BRIDGE :: REG_SEMAPHORE_1 :: semaphore [07:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_1_semaphore_MASK      0x000000ff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_1_semaphore_SHIFT     0

/***************************************************************************
 *REG_SEMAPHORE_2 - CPU semaphore #2
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SEMAPHORE_2 :: reserved0 [31:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_2_reserved0_MASK      0xffffff00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_2_reserved0_SHIFT     8

/* OFE_ARMCR4_BRIDGE :: REG_SEMAPHORE_2 :: semaphore [07:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_2_semaphore_MASK      0x000000ff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_2_semaphore_SHIFT     0

/***************************************************************************
 *REG_SEMAPHORE_3 - CPU semaphore #3
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SEMAPHORE_3 :: reserved0 [31:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_3_reserved0_MASK      0xffffff00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_3_reserved0_SHIFT     8

/* OFE_ARMCR4_BRIDGE :: REG_SEMAPHORE_3 :: semaphore [07:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_3_semaphore_MASK      0x000000ff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_3_semaphore_SHIFT     0

/***************************************************************************
 *REG_SEMAPHORE_4 - CPU semaphore #4
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SEMAPHORE_4 :: reserved0 [31:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_4_reserved0_MASK      0xffffff00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_4_reserved0_SHIFT     8

/* OFE_ARMCR4_BRIDGE :: REG_SEMAPHORE_4 :: semaphore [07:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_4_semaphore_MASK      0x000000ff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SEMAPHORE_4_semaphore_SHIFT     0

/***************************************************************************
 *REG_SCRATCH_1 - CPU scratchpad #1
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SCRATCH_1 :: data [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_1_data_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_1_data_SHIFT            0

/***************************************************************************
 *REG_SCRATCH_2 - CPU scratchpad #2
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SCRATCH_2 :: data [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_2_data_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_2_data_SHIFT            0

/***************************************************************************
 *REG_SCRATCH_3 - CPU scratchpad #3
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SCRATCH_3 :: data [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_3_data_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_3_data_SHIFT            0

/***************************************************************************
 *REG_SCRATCH_4 - CPU scratchpad #4
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SCRATCH_4 :: data [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_4_data_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_4_data_SHIFT            0

/***************************************************************************
 *REG_SCRATCH_5 - CPU scratchpad #5
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SCRATCH_5 :: data [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_5_data_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_5_data_SHIFT            0

/***************************************************************************
 *REG_SCRATCH_6 - CPU scratchpad #6
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SCRATCH_6 :: data [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_6_data_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_6_data_SHIFT            0

/***************************************************************************
 *REG_SCRATCH_7 - CPU scratchpad #7
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SCRATCH_7 :: data [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_7_data_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_7_data_SHIFT            0

/***************************************************************************
 *REG_SCRATCH_8 - CPU scratchpad #8
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SCRATCH_8 :: data [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_8_data_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_8_data_SHIFT            0

/***************************************************************************
 *REG_SCRATCH_9 - CPU scratchpad #9
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_SCRATCH_9 :: data [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_9_data_MASK             0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_SCRATCH_9_data_SHIFT            0

/***************************************************************************
 *REG_PERF_CONFIG - Performance monitor configuration
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_PERF_CONFIG :: reserved0 [31:01] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_CONFIG_reserved0_MASK      0xfffffffe
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_CONFIG_reserved0_SHIFT     1

/* OFE_ARMCR4_BRIDGE :: REG_PERF_CONFIG :: enable [00:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_CONFIG_enable_MASK         0x00000001
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_CONFIG_enable_SHIFT        0

/***************************************************************************
 *REG_PERF_LIMIT - Performance monitor count threshold
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_PERF_LIMIT :: count [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_LIMIT_count_MASK           0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_LIMIT_count_SHIFT          0

/***************************************************************************
 *REG_PERF_WR_CNT - Counts the number of merge buffer updates (hits + misses)
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_PERF_WR_CNT :: count [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_WR_CNT_count_MASK          0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_WR_CNT_count_SHIFT         0

/***************************************************************************
 *REG_PERF_WR_MISS - Counts the number of merge buffer misses
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_PERF_WR_MISS :: count [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_WR_MISS_count_MASK         0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_WR_MISS_count_SHIFT        0

/***************************************************************************
 *REG_PERF_RD_CNT - Counts the number of prefetch buffer accesses (hits + misses)
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_PERF_RD_CNT :: count [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_RD_CNT_count_MASK          0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_RD_CNT_count_SHIFT         0

/***************************************************************************
 *REG_PERF_RD_MISS - Counts the number of prefetch buffer misses
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_PERF_RD_MISS :: count [31:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_RD_MISS_count_MASK         0xffffffff
#define BCHP_OFE_ARMCR4_BRIDGE_REG_PERF_RD_MISS_count_SHIFT        0

/***************************************************************************
 *REG_MEMORY_TM1 - ARM memory TM1 control register
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM1 :: tm_dc7 [31:28] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc7_MASK          0xf0000000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc7_SHIFT         28

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM1 :: tm_dc6 [27:24] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc6_MASK          0x0f000000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc6_SHIFT         24

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM1 :: tm_dc5 [23:20] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc5_MASK          0x00f00000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc5_SHIFT         20

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM1 :: tm_dc4 [19:16] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc4_MASK          0x000f0000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc4_SHIFT         16

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM1 :: tm_dc3 [15:12] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc3_MASK          0x0000f000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc3_SHIFT         12

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM1 :: tm_dc2 [11:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc2_MASK          0x00000f00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc2_SHIFT         8

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM1 :: tm_dc1 [07:04] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc1_MASK          0x000000f0
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc1_SHIFT         4

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM1 :: tm_dc0 [03:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc0_MASK          0x0000000f
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM1_tm_dc0_SHIFT         0

/***************************************************************************
 *REG_MEMORY_TM2 - ARM memory TM2 control register
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM2 :: reserved0 [31:24] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_reserved0_MASK       0xff000000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_reserved0_SHIFT      24

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM2 :: tm_tcm_upper [23:20] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_tcm_upper_MASK    0x00f00000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_tcm_upper_SHIFT   20

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM2 :: tm_tcm_low [19:16] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_tcm_low_MASK      0x000f0000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_tcm_low_SHIFT     16

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM2 :: tm_ic6 [15:12] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_ic6_MASK          0x0000f000
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_ic6_SHIFT         12

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM2 :: tm_ic4 [11:08] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_ic4_MASK          0x00000f00
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_ic4_SHIFT         8

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM2 :: tm_ic2 [07:04] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_ic2_MASK          0x000000f0
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_ic2_SHIFT         4

/* OFE_ARMCR4_BRIDGE :: REG_MEMORY_TM2 :: tm_ic0 [03:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_ic0_MASK          0x0000000f
#define BCHP_OFE_ARMCR4_BRIDGE_REG_MEMORY_TM2_tm_ic0_SHIFT         0

/***************************************************************************
 *REG_ARM_HALT - ARM halt register - keeps the processor from fetching instructions after reset
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_ARM_HALT :: reserved0 [31:01] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_HALT_reserved0_MASK         0xfffffffe
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_HALT_reserved0_SHIFT        1

/* OFE_ARMCR4_BRIDGE :: REG_ARM_HALT :: ARM_HALT_N [00:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_HALT_ARM_HALT_N_MASK        0x00000001
#define BCHP_OFE_ARMCR4_BRIDGE_REG_ARM_HALT_ARM_HALT_N_SHIFT       0

/***************************************************************************
 *REG_FIFO_STATUS - Fifo Status
 ***************************************************************************/
/* OFE_ARMCR4_BRIDGE :: REG_FIFO_STATUS :: reserved0 [31:02] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_FIFO_STATUS_reserved0_MASK      0xfffffffc
#define BCHP_OFE_ARMCR4_BRIDGE_REG_FIFO_STATUS_reserved0_SHIFT     2

/* OFE_ARMCR4_BRIDGE :: REG_FIFO_STATUS :: CCB_RD_FULL [01:01] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_FIFO_STATUS_CCB_RD_FULL_MASK    0x00000002
#define BCHP_OFE_ARMCR4_BRIDGE_REG_FIFO_STATUS_CCB_RD_FULL_SHIFT   1

/* OFE_ARMCR4_BRIDGE :: REG_FIFO_STATUS :: CCB_WR_FULL [00:00] */
#define BCHP_OFE_ARMCR4_BRIDGE_REG_FIFO_STATUS_CCB_WR_FULL_MASK    0x00000001
#define BCHP_OFE_ARMCR4_BRIDGE_REG_FIFO_STATUS_CCB_WR_FULL_SHIFT   0

#endif /* #ifndef BCHP_OFE_ARMCR4_BRIDGE_H__ */

/* End of File */
