/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_pcix_bridge_1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 12/2/08 7:00p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Dec  2 14:04:31 2008
 *                 MD5 Checksum         90975bbcdf76045bb6bd092e6bdf481b
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7635/rdb/a0/bchp_pcix_bridge_1.h $
 * 
 * Hydra_Software_Devel/1   12/2/08 7:00p albertl
 * PR48688: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_PCIX_BRIDGE_1_H__
#define BCHP_PCIX_BRIDGE_1_H__

/***************************************************************************
 *PCIX_BRIDGE_1 - SATA PCIX Bridge Registers 1
 ***************************************************************************/
#define BCHP_PCIX_BRIDGE_1_REVISION              0x00580200 /* PCIX Bridge Revision Register */
#define BCHP_PCIX_BRIDGE_1_PCIX_CTRL             0x00580204 /* PCIX Bridge Control */
#define BCHP_PCIX_BRIDGE_1_SATA_CFG_INDEX        0x00580208 /* Serial ATA Configuration Access Address */
#define BCHP_PCIX_BRIDGE_1_SATA_CFG_DATA         0x0058020c /* Serial ATA Configuration Access Data */
#define BCHP_PCIX_BRIDGE_1_PCIX_SLV_MEM_WIN_BASE 0x00580210 /* PCIX SCB Slave Memory Window Base Address */
#define BCHP_PCIX_BRIDGE_1_PCIX_SLV_MEM_WIN_MODE 0x00580214 /* PCIX SCB Slave Memory Window Mode Address */
#define BCHP_PCIX_BRIDGE_1_CPU_TO_SATA_MEM_WIN_BASE 0x00580218 /* CPU to SATA PCIX Memory Window Base Address */
#define BCHP_PCIX_BRIDGE_1_CPU_TO_SATA_IO_WIN_BASE 0x0058021c /* CPU to SATA PCIX IO Window Base Address */
#define BCHP_PCIX_BRIDGE_1_RETRY_TIMER           0x00580220 /* Master interface retry timeout counter */
#define BCHP_PCIX_BRIDGE_1_SCRATCH               0x00580234 /* PCIX Bridge Scratch register */
#define BCHP_PCIX_BRIDGE_1_DEBUGGER_MBIST_TM_CTRL 0x00580238 /* PCIX Bridge Testport Output register */
#define BCHP_PCIX_BRIDGE_1_TP_OUT                0x0058023c /* PCIX Bridge Testport Output Register */

#endif /* #ifndef BCHP_PCIX_BRIDGE_1_H__ */

/* End of File */
