/***************************************************************************
 *     Copyright (c) 1999-2008, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_ddr23_ctl_regs_0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 12/2/08 5:48p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Dec  2 14:04:55 2008
 *                 MD5 Checksum         90975bbcdf76045bb6bd092e6bdf481b
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7635/rdb/a0/bchp_ddr23_ctl_regs_0.h $
 * 
 * Hydra_Software_Devel/1   12/2/08 5:48p albertl
 * PR48688: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_DDR23_CTL_REGS_0_H__
#define BCHP_DDR23_CTL_REGS_0_H__

/***************************************************************************
 *DDR23_CTL_REGS_0 - DDR23 controller registers 0
 ***************************************************************************/
#define BCHP_DDR23_CTL_REGS_0_REVISION           0x01800000 /* DDR23 Controller revision register */
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS         0x01800004 /* DDR23 Controller status register */
#define BCHP_DDR23_CTL_REGS_0_PARAMS1            0x01800010 /* DDR23 Controller Configuration Set #1 */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2            0x01800014 /* DDR23 Controller Configuration Set #2 */
#define BCHP_DDR23_CTL_REGS_0_PARAMS3            0x01800018 /* DDR23 Controller Configuration Set #3 */
#define BCHP_DDR23_CTL_REGS_0_REFRESH            0x0180001c /* DDR23 Controller Automated Refresh Configuration */
#define BCHP_DDR23_CTL_REGS_0_REFRESH_CMD        0x01800020 /* Host Initiated Refresh Control */
#define BCHP_DDR23_CTL_REGS_0_PRECHARGE_CMD      0x01800024 /* Host Initiated Precharge Control */
#define BCHP_DDR23_CTL_REGS_0_LOAD_MODE_CMD      0x01800028 /* Host Initiated Load Mode Control */
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE_CMD     0x0180002c /* Host Initiated Load Extended Mode Control */
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE2_CMD    0x01800030 /* Host Initiated Load Extended Mode #2 Control */
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE3_CMD    0x01800034 /* Host Initiated Load Extended Mode #3 Control */
#define BCHP_DDR23_CTL_REGS_0_ZQ_CALIBRATE       0x01800038 /* Host Initiated ZQ Calibration Cycle */
#define BCHP_DDR23_CTL_REGS_0_CMD_STATUS         0x0180003c /* Host Command Interface Status */
#define BCHP_DDR23_CTL_REGS_0_LATENCY            0x01800040 /* DDR2 Controller Access Latency Control */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE0         0x01800044 /* Semaphore Register #0 */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE1         0x01800048 /* Semaphore Register #1 */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE2         0x0180004c /* Semaphore Register #2 */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE3         0x01800050 /* Semaphore Register #3 */
#define BCHP_DDR23_CTL_REGS_0_SCRATCH            0x01800058 /* Scratch Register */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_WIDTH       0x01800060 /* Stripe Width */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_0    0x01800070 /* Stripe Height for picture buffers 0 through 23 */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_1    0x01800074 /* Stripe Height for picture buffers 24 through 27 */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_2    0x01800078 /* Stripe Height for picture buffers 28 through 31 */
#define BCHP_DDR23_CTL_REGS_0_LBIST_CNTRL        0x018000a0 /* Logic-Bist Control and Status */
#define BCHP_DDR23_CTL_REGS_0_LBIST_SEED         0x018000a4 /* Logic-Bist PRPG Seed Value */
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS       0x018000a8 /* Logic-Bist Control and Status */
#define BCHP_DDR23_CTL_REGS_0_VDL_CTL            0x018000b0 /* Dynamic VDL Changes Control */
#define BCHP_DDR23_CTL_REGS_0_VDL_ADR_BASE       0x018000b4 /* Dynamic VDL Changes Base Address */
#define BCHP_DDR23_CTL_REGS_0_VDL_ADR_END        0x018000b8 /* Dynamic VDL Changes End Address */
#define BCHP_DDR23_CTL_REGS_0_PMON_CTL           0x018000c0 /* Performance Monitoring Control */
#define BCHP_DDR23_CTL_REGS_0_PMON_PERIOD        0x018000c4 /* Performance Monitoring Period Control */
#define BCHP_DDR23_CTL_REGS_0_PMON_CYCLE_CNT     0x018000c8 /* Performance Monitoring Active Cycles Count */
#define BCHP_DDR23_CTL_REGS_0_PMON_IDLE_CNT      0x018000cc /* Performance Monitoring Idle Cycles Count */
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT1       0x018000d0 /* Performance Monitoring Data Channel #1 Read Accesses Count */
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT2       0x018000d4 /* Performance Monitoring Data Channel #2 Read Accesses Count */
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT3       0x018000d8 /* Performance Monitoring Data Channel #3 Read Accesses Count */
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT1       0x018000dc /* Performance Monitoring Data Channel #1 Write Accesses Count */
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT2       0x018000e0 /* Performance Monitoring Data Channel #2 Write Accesses Count */
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT3       0x018000e4 /* Performance Monitoring Data Channel #3 Write Accesses Count */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM             0x018000e8 /* RAM Macro TM Control */

/***************************************************************************
 *REVISION - DDR23 Controller revision register
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: REVISION :: reserved0 [31:16] */
#define BCHP_DDR23_CTL_REGS_0_REVISION_reserved0_MASK              0xffff0000
#define BCHP_DDR23_CTL_REGS_0_REVISION_reserved0_SHIFT             16

/* DDR23_CTL_REGS_0 :: REVISION :: MAJOR [15:08] */
#define BCHP_DDR23_CTL_REGS_0_REVISION_MAJOR_MASK                  0x0000ff00
#define BCHP_DDR23_CTL_REGS_0_REVISION_MAJOR_SHIFT                 8

/* DDR23_CTL_REGS_0 :: REVISION :: MINOR [07:00] */
#define BCHP_DDR23_CTL_REGS_0_REVISION_MINOR_MASK                  0x000000ff
#define BCHP_DDR23_CTL_REGS_0_REVISION_MINOR_SHIFT                 0

/***************************************************************************
 *CTL_STATUS - DDR23 Controller status register
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: CTL_STATUS :: reserved0 [31:07] */
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_reserved0_MASK            0xffffff80
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_reserved0_SHIFT           7

/* DDR23_CTL_REGS_0 :: CTL_STATUS :: rd_fifo3_empty [06:06] */
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_rd_fifo3_empty_MASK       0x00000040
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_rd_fifo3_empty_SHIFT      6

/* DDR23_CTL_REGS_0 :: CTL_STATUS :: rd_fifo2_empty [05:05] */
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_rd_fifo2_empty_MASK       0x00000020
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_rd_fifo2_empty_SHIFT      5

/* DDR23_CTL_REGS_0 :: CTL_STATUS :: rd_fifo1_empty [04:04] */
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_rd_fifo1_empty_MASK       0x00000010
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_rd_fifo1_empty_SHIFT      4

/* DDR23_CTL_REGS_0 :: CTL_STATUS :: reserved1 [03:02] */
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_reserved1_MASK            0x0000000c
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_reserved1_SHIFT           2

/* DDR23_CTL_REGS_0 :: CTL_STATUS :: clke [01:01] */
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_clke_MASK                 0x00000002
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_clke_SHIFT                1

/* DDR23_CTL_REGS_0 :: CTL_STATUS :: idle [00:00] */
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_idle_MASK                 0x00000001
#define BCHP_DDR23_CTL_REGS_0_CTL_STATUS_idle_SHIFT                0

/***************************************************************************
 *PARAMS1 - DDR23 Controller Configuration Set #1
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PARAMS1 :: trtp [31:28] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_trtp_MASK                    0xf0000000
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_trtp_SHIFT                   28

/* DDR23_CTL_REGS_0 :: PARAMS1 :: twl [27:24] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_twl_MASK                     0x0f000000
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_twl_SHIFT                    24

/* DDR23_CTL_REGS_0 :: PARAMS1 :: tcas [23:20] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_tcas_MASK                    0x00f00000
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_tcas_SHIFT                   20

/* DDR23_CTL_REGS_0 :: PARAMS1 :: twtr [19:16] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_twtr_MASK                    0x000f0000
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_twtr_SHIFT                   16

/* DDR23_CTL_REGS_0 :: PARAMS1 :: twr [15:12] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_twr_MASK                     0x0000f000
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_twr_SHIFT                    12

/* DDR23_CTL_REGS_0 :: PARAMS1 :: trrd [11:08] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_trrd_MASK                    0x00000f00
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_trrd_SHIFT                   8

/* DDR23_CTL_REGS_0 :: PARAMS1 :: trp [07:04] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_trp_MASK                     0x000000f0
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_trp_SHIFT                    4

/* DDR23_CTL_REGS_0 :: PARAMS1 :: trcd [03:00] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_trcd_MASK                    0x0000000f
#define BCHP_DDR23_CTL_REGS_0_PARAMS1_trcd_SHIFT                   0

/***************************************************************************
 *PARAMS2 - DDR23 Controller Configuration Set #2
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PARAMS2 :: auto_idle [31:31] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_auto_idle_MASK               0x80000000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_auto_idle_SHIFT              31

/* DDR23_CTL_REGS_0 :: PARAMS2 :: row_bits [30:30] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_row_bits_MASK                0x40000000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_row_bits_SHIFT               30

/* DDR23_CTL_REGS_0 :: PARAMS2 :: use_chr_hgt [29:29] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_use_chr_hgt_MASK             0x20000000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_use_chr_hgt_SHIFT            29

/* DDR23_CTL_REGS_0 :: PARAMS2 :: clke [28:28] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_clke_MASK                    0x10000000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_clke_SHIFT                   28

/* DDR23_CTL_REGS_0 :: PARAMS2 :: sd_col_bits [27:26] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_sd_col_bits_MASK             0x0c000000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_sd_col_bits_SHIFT            26

/* DDR23_CTL_REGS_0 :: PARAMS2 :: il_sel [25:25] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_il_sel_MASK                  0x02000000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_il_sel_SHIFT                 25

/* DDR23_CTL_REGS_0 :: PARAMS2 :: dis_itlv [24:24] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_dis_itlv_MASK                0x01000000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_dis_itlv_SHIFT               24

/* DDR23_CTL_REGS_0 :: PARAMS2 :: reserved0 [23:23] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_reserved0_MASK               0x00800000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_reserved0_SHIFT              23

/* DDR23_CTL_REGS_0 :: PARAMS2 :: cs0_only [22:22] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_cs0_only_MASK                0x00400000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_cs0_only_SHIFT               22

/* DDR23_CTL_REGS_0 :: PARAMS2 :: allow_pictmem_rd [21:21] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_allow_pictmem_rd_MASK        0x00200000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_allow_pictmem_rd_SHIFT       21

/* DDR23_CTL_REGS_0 :: PARAMS2 :: bank_bits [20:20] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_bank_bits_MASK               0x00100000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_bank_bits_SHIFT              20

/* DDR23_CTL_REGS_0 :: PARAMS2 :: trfc [19:12] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_trfc_MASK                    0x000ff000
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_trfc_SHIFT                   12

/* DDR23_CTL_REGS_0 :: PARAMS2 :: tfaw [11:06] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_tfaw_MASK                    0x00000fc0
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_tfaw_SHIFT                   6

/* DDR23_CTL_REGS_0 :: PARAMS2 :: tras [05:00] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_tras_MASK                    0x0000003f
#define BCHP_DDR23_CTL_REGS_0_PARAMS2_tras_SHIFT                   0

/***************************************************************************
 *PARAMS3 - DDR23 Controller Configuration Set #3
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PARAMS3 :: reserved0 [31:06] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_reserved0_MASK               0xffffffc0
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_reserved0_SHIFT              6

/* DDR23_CTL_REGS_0 :: PARAMS3 :: ddr_bl [05:05] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_ddr_bl_MASK                  0x00000020
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_ddr_bl_SHIFT                 5

/* DDR23_CTL_REGS_0 :: PARAMS3 :: cmd_2t [04:04] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_cmd_2t_MASK                  0x00000010
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_cmd_2t_SHIFT                 4

/* DDR23_CTL_REGS_0 :: PARAMS3 :: reserved1 [03:03] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_reserved1_MASK               0x00000008
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_reserved1_SHIFT              3

/* DDR23_CTL_REGS_0 :: PARAMS3 :: wr_odt_mode [02:02] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_wr_odt_mode_MASK             0x00000004
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_wr_odt_mode_SHIFT            2

/* DDR23_CTL_REGS_0 :: PARAMS3 :: wr_odt_adj [01:01] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_wr_odt_adj_MASK              0x00000002
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_wr_odt_adj_SHIFT             1

/* DDR23_CTL_REGS_0 :: PARAMS3 :: wr_odt_en [00:00] */
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_wr_odt_en_MASK               0x00000001
#define BCHP_DDR23_CTL_REGS_0_PARAMS3_wr_odt_en_SHIFT              0

/***************************************************************************
 *REFRESH - DDR23 Controller Automated Refresh Configuration
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: REFRESH :: reserved0 [31:13] */
#define BCHP_DDR23_CTL_REGS_0_REFRESH_reserved0_MASK               0xffffe000
#define BCHP_DDR23_CTL_REGS_0_REFRESH_reserved0_SHIFT              13

/* DDR23_CTL_REGS_0 :: REFRESH :: enable [12:12] */
#define BCHP_DDR23_CTL_REGS_0_REFRESH_enable_MASK                  0x00001000
#define BCHP_DDR23_CTL_REGS_0_REFRESH_enable_SHIFT                 12

/* DDR23_CTL_REGS_0 :: REFRESH :: period [11:00] */
#define BCHP_DDR23_CTL_REGS_0_REFRESH_period_MASK                  0x00000fff
#define BCHP_DDR23_CTL_REGS_0_REFRESH_period_SHIFT                 0

/***************************************************************************
 *REFRESH_CMD - Host Initiated Refresh Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: REFRESH_CMD :: reserved0 [31:16] */
#define BCHP_DDR23_CTL_REGS_0_REFRESH_CMD_reserved0_MASK           0xffff0000
#define BCHP_DDR23_CTL_REGS_0_REFRESH_CMD_reserved0_SHIFT          16

/* DDR23_CTL_REGS_0 :: REFRESH_CMD :: cmd [15:00] */
#define BCHP_DDR23_CTL_REGS_0_REFRESH_CMD_cmd_MASK                 0x0000ffff
#define BCHP_DDR23_CTL_REGS_0_REFRESH_CMD_cmd_SHIFT                0

/***************************************************************************
 *PRECHARGE_CMD - Host Initiated Precharge Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PRECHARGE_CMD :: reserved0 [31:16] */
#define BCHP_DDR23_CTL_REGS_0_PRECHARGE_CMD_reserved0_MASK         0xffff0000
#define BCHP_DDR23_CTL_REGS_0_PRECHARGE_CMD_reserved0_SHIFT        16

/* DDR23_CTL_REGS_0 :: PRECHARGE_CMD :: cmd [15:00] */
#define BCHP_DDR23_CTL_REGS_0_PRECHARGE_CMD_cmd_MASK               0x0000ffff
#define BCHP_DDR23_CTL_REGS_0_PRECHARGE_CMD_cmd_SHIFT              0

/***************************************************************************
 *LOAD_MODE_CMD - Host Initiated Load Mode Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: LOAD_MODE_CMD :: reserved0 [31:16] */
#define BCHP_DDR23_CTL_REGS_0_LOAD_MODE_CMD_reserved0_MASK         0xffff0000
#define BCHP_DDR23_CTL_REGS_0_LOAD_MODE_CMD_reserved0_SHIFT        16

/* DDR23_CTL_REGS_0 :: LOAD_MODE_CMD :: cmd [15:00] */
#define BCHP_DDR23_CTL_REGS_0_LOAD_MODE_CMD_cmd_MASK               0x0000ffff
#define BCHP_DDR23_CTL_REGS_0_LOAD_MODE_CMD_cmd_SHIFT              0

/***************************************************************************
 *LOAD_EMODE_CMD - Host Initiated Load Extended Mode Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: LOAD_EMODE_CMD :: reserved0 [31:16] */
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE_CMD_reserved0_MASK        0xffff0000
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE_CMD_reserved0_SHIFT       16

/* DDR23_CTL_REGS_0 :: LOAD_EMODE_CMD :: cmd [15:00] */
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE_CMD_cmd_MASK              0x0000ffff
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE_CMD_cmd_SHIFT             0

/***************************************************************************
 *LOAD_EMODE2_CMD - Host Initiated Load Extended Mode #2 Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: LOAD_EMODE2_CMD :: reserved0 [31:16] */
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE2_CMD_reserved0_MASK       0xffff0000
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE2_CMD_reserved0_SHIFT      16

/* DDR23_CTL_REGS_0 :: LOAD_EMODE2_CMD :: cmd [15:00] */
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE2_CMD_cmd_MASK             0x0000ffff
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE2_CMD_cmd_SHIFT            0

/***************************************************************************
 *LOAD_EMODE3_CMD - Host Initiated Load Extended Mode #3 Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: LOAD_EMODE3_CMD :: reserved0 [31:16] */
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE3_CMD_reserved0_MASK       0xffff0000
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE3_CMD_reserved0_SHIFT      16

/* DDR23_CTL_REGS_0 :: LOAD_EMODE3_CMD :: cmd [15:00] */
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE3_CMD_cmd_MASK             0x0000ffff
#define BCHP_DDR23_CTL_REGS_0_LOAD_EMODE3_CMD_cmd_SHIFT            0

/***************************************************************************
 *ZQ_CALIBRATE - Host Initiated ZQ Calibration Cycle
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: ZQ_CALIBRATE :: reserved0 [31:16] */
#define BCHP_DDR23_CTL_REGS_0_ZQ_CALIBRATE_reserved0_MASK          0xffff0000
#define BCHP_DDR23_CTL_REGS_0_ZQ_CALIBRATE_reserved0_SHIFT         16

/* DDR23_CTL_REGS_0 :: ZQ_CALIBRATE :: cmd [15:00] */
#define BCHP_DDR23_CTL_REGS_0_ZQ_CALIBRATE_cmd_MASK                0x0000ffff
#define BCHP_DDR23_CTL_REGS_0_ZQ_CALIBRATE_cmd_SHIFT               0

/***************************************************************************
 *CMD_STATUS - Host Command Interface Status
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: CMD_STATUS :: reserved0 [31:01] */
#define BCHP_DDR23_CTL_REGS_0_CMD_STATUS_reserved0_MASK            0xfffffffe
#define BCHP_DDR23_CTL_REGS_0_CMD_STATUS_reserved0_SHIFT           1

/* DDR23_CTL_REGS_0 :: CMD_STATUS :: status [00:00] */
#define BCHP_DDR23_CTL_REGS_0_CMD_STATUS_status_MASK               0x00000001
#define BCHP_DDR23_CTL_REGS_0_CMD_STATUS_status_SHIFT              0

/***************************************************************************
 *LATENCY - DDR2 Controller Access Latency Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: LATENCY :: reserved0 [31:10] */
#define BCHP_DDR23_CTL_REGS_0_LATENCY_reserved0_MASK               0xfffffc00
#define BCHP_DDR23_CTL_REGS_0_LATENCY_reserved0_SHIFT              10

/* DDR23_CTL_REGS_0 :: LATENCY :: limit [09:00] */
#define BCHP_DDR23_CTL_REGS_0_LATENCY_limit_MASK                   0x000003ff
#define BCHP_DDR23_CTL_REGS_0_LATENCY_limit_SHIFT                  0

/***************************************************************************
 *SEMAPHORE0 - Semaphore Register #0
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: SEMAPHORE0 :: reserved0 [31:01] */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE0_reserved0_MASK            0xfffffffe
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE0_reserved0_SHIFT           1

/* DDR23_CTL_REGS_0 :: SEMAPHORE0 :: enable [00:00] */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE0_enable_MASK               0x00000001
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE0_enable_SHIFT              0

/***************************************************************************
 *SEMAPHORE1 - Semaphore Register #1
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: SEMAPHORE1 :: reserved0 [31:01] */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE1_reserved0_MASK            0xfffffffe
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE1_reserved0_SHIFT           1

/* DDR23_CTL_REGS_0 :: SEMAPHORE1 :: enable [00:00] */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE1_enable_MASK               0x00000001
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE1_enable_SHIFT              0

/***************************************************************************
 *SEMAPHORE2 - Semaphore Register #2
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: SEMAPHORE2 :: reserved0 [31:01] */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE2_reserved0_MASK            0xfffffffe
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE2_reserved0_SHIFT           1

/* DDR23_CTL_REGS_0 :: SEMAPHORE2 :: enable [00:00] */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE2_enable_MASK               0x00000001
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE2_enable_SHIFT              0

/***************************************************************************
 *SEMAPHORE3 - Semaphore Register #3
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: SEMAPHORE3 :: reserved0 [31:01] */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE3_reserved0_MASK            0xfffffffe
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE3_reserved0_SHIFT           1

/* DDR23_CTL_REGS_0 :: SEMAPHORE3 :: enable [00:00] */
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE3_enable_MASK               0x00000001
#define BCHP_DDR23_CTL_REGS_0_SEMAPHORE3_enable_SHIFT              0

/***************************************************************************
 *SCRATCH - Scratch Register
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: SCRATCH :: scratch [31:00] */
#define BCHP_DDR23_CTL_REGS_0_SCRATCH_scratch_MASK                 0xffffffff
#define BCHP_DDR23_CTL_REGS_0_SCRATCH_scratch_SHIFT                0

/***************************************************************************
 *STRIPE_WIDTH - Stripe Width
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: STRIPE_WIDTH :: reserved0 [31:02] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_WIDTH_reserved0_MASK          0xfffffffc
#define BCHP_DDR23_CTL_REGS_0_STRIPE_WIDTH_reserved0_SHIFT         2

/* DDR23_CTL_REGS_0 :: STRIPE_WIDTH :: swidth [01:00] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_WIDTH_swidth_MASK             0x00000003
#define BCHP_DDR23_CTL_REGS_0_STRIPE_WIDTH_swidth_SHIFT            0

/***************************************************************************
 *STRIPE_HEIGHT_0 - Stripe Height for picture buffers 0 through 23
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_0 :: reserved0 [31:27] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_0_reserved0_MASK       0xf8000000
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_0_reserved0_SHIFT      27

/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_0 :: chroma_height [26:16] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_0_chroma_height_MASK   0x07ff0000
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_0_chroma_height_SHIFT  16

/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_0 :: reserved1 [15:11] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_0_reserved1_MASK       0x0000f800
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_0_reserved1_SHIFT      11

/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_0 :: luma_height [10:00] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_0_luma_height_MASK     0x000007ff
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_0_luma_height_SHIFT    0

/***************************************************************************
 *STRIPE_HEIGHT_1 - Stripe Height for picture buffers 24 through 27
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_1 :: reserved0 [31:27] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_1_reserved0_MASK       0xf8000000
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_1_reserved0_SHIFT      27

/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_1 :: chroma_height [26:16] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_1_chroma_height_MASK   0x07ff0000
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_1_chroma_height_SHIFT  16

/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_1 :: reserved1 [15:11] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_1_reserved1_MASK       0x0000f800
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_1_reserved1_SHIFT      11

/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_1 :: luma_height [10:00] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_1_luma_height_MASK     0x000007ff
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_1_luma_height_SHIFT    0

/***************************************************************************
 *STRIPE_HEIGHT_2 - Stripe Height for picture buffers 28 through 31
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_2 :: reserved0 [31:27] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_2_reserved0_MASK       0xf8000000
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_2_reserved0_SHIFT      27

/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_2 :: chroma_height [26:16] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_2_chroma_height_MASK   0x07ff0000
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_2_chroma_height_SHIFT  16

/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_2 :: reserved1 [15:11] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_2_reserved1_MASK       0x0000f800
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_2_reserved1_SHIFT      11

/* DDR23_CTL_REGS_0 :: STRIPE_HEIGHT_2 :: luma_height [10:00] */
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_2_luma_height_MASK     0x000007ff
#define BCHP_DDR23_CTL_REGS_0_STRIPE_HEIGHT_2_luma_height_SHIFT    0

/***************************************************************************
 *LBIST_CNTRL - Logic-Bist Control and Status
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: LBIST_CNTRL :: reserved0 [31:02] */
#define BCHP_DDR23_CTL_REGS_0_LBIST_CNTRL_reserved0_MASK           0xfffffffc
#define BCHP_DDR23_CTL_REGS_0_LBIST_CNTRL_reserved0_SHIFT          2

/* DDR23_CTL_REGS_0 :: LBIST_CNTRL :: ckdis [01:01] */
#define BCHP_DDR23_CTL_REGS_0_LBIST_CNTRL_ckdis_MASK               0x00000002
#define BCHP_DDR23_CTL_REGS_0_LBIST_CNTRL_ckdis_SHIFT              1

/* DDR23_CTL_REGS_0 :: LBIST_CNTRL :: enable [00:00] */
#define BCHP_DDR23_CTL_REGS_0_LBIST_CNTRL_enable_MASK              0x00000001
#define BCHP_DDR23_CTL_REGS_0_LBIST_CNTRL_enable_SHIFT             0

/***************************************************************************
 *LBIST_SEED - Logic-Bist PRPG Seed Value
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: LBIST_SEED :: seed [31:00] */
#define BCHP_DDR23_CTL_REGS_0_LBIST_SEED_seed_MASK                 0xffffffff
#define BCHP_DDR23_CTL_REGS_0_LBIST_SEED_seed_SHIFT                0

/***************************************************************************
 *LBIST_STATUS - Logic-Bist Control and Status
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: LBIST_STATUS :: reserved0 [31:04] */
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_reserved0_MASK          0xfffffff0
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_reserved0_SHIFT         4

/* DDR23_CTL_REGS_0 :: LBIST_STATUS :: dat_pass [03:03] */
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_dat_pass_MASK           0x00000008
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_dat_pass_SHIFT          3

/* DDR23_CTL_REGS_0 :: LBIST_STATUS :: ctl_pass [02:02] */
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_ctl_pass_MASK           0x00000004
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_ctl_pass_SHIFT          2

/* DDR23_CTL_REGS_0 :: LBIST_STATUS :: dat_done [01:01] */
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_dat_done_MASK           0x00000002
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_dat_done_SHIFT          1

/* DDR23_CTL_REGS_0 :: LBIST_STATUS :: ctl_done [00:00] */
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_ctl_done_MASK           0x00000001
#define BCHP_DDR23_CTL_REGS_0_LBIST_STATUS_ctl_done_SHIFT          0

/***************************************************************************
 *VDL_CTL - Dynamic VDL Changes Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: VDL_CTL :: reserved0 [31:01] */
#define BCHP_DDR23_CTL_REGS_0_VDL_CTL_reserved0_MASK               0xfffffffe
#define BCHP_DDR23_CTL_REGS_0_VDL_CTL_reserved0_SHIFT              1

/* DDR23_CTL_REGS_0 :: VDL_CTL :: enable [00:00] */
#define BCHP_DDR23_CTL_REGS_0_VDL_CTL_enable_MASK                  0x00000001
#define BCHP_DDR23_CTL_REGS_0_VDL_CTL_enable_SHIFT                 0

/***************************************************************************
 *VDL_ADR_BASE - Dynamic VDL Changes Base Address
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: VDL_ADR_BASE :: addr [31:00] */
#define BCHP_DDR23_CTL_REGS_0_VDL_ADR_BASE_addr_MASK               0xffffffff
#define BCHP_DDR23_CTL_REGS_0_VDL_ADR_BASE_addr_SHIFT              0

/***************************************************************************
 *VDL_ADR_END - Dynamic VDL Changes End Address
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: VDL_ADR_END :: addr [31:00] */
#define BCHP_DDR23_CTL_REGS_0_VDL_ADR_END_addr_MASK                0xffffffff
#define BCHP_DDR23_CTL_REGS_0_VDL_ADR_END_addr_SHIFT               0

/***************************************************************************
 *PMON_CTL - Performance Monitoring Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_CTL :: reserved0 [31:01] */
#define BCHP_DDR23_CTL_REGS_0_PMON_CTL_reserved0_MASK              0xfffffffe
#define BCHP_DDR23_CTL_REGS_0_PMON_CTL_reserved0_SHIFT             1

/* DDR23_CTL_REGS_0 :: PMON_CTL :: enable [00:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_CTL_enable_MASK                 0x00000001
#define BCHP_DDR23_CTL_REGS_0_PMON_CTL_enable_SHIFT                0

/***************************************************************************
 *PMON_PERIOD - Performance Monitoring Period Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_PERIOD :: reserved0 [31:24] */
#define BCHP_DDR23_CTL_REGS_0_PMON_PERIOD_reserved0_MASK           0xff000000
#define BCHP_DDR23_CTL_REGS_0_PMON_PERIOD_reserved0_SHIFT          24

/* DDR23_CTL_REGS_0 :: PMON_PERIOD :: count [23:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_PERIOD_count_MASK               0x00ffffff
#define BCHP_DDR23_CTL_REGS_0_PMON_PERIOD_count_SHIFT              0

/***************************************************************************
 *PMON_CYCLE_CNT - Performance Monitoring Active Cycles Count
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_CYCLE_CNT :: reserved0 [31:24] */
#define BCHP_DDR23_CTL_REGS_0_PMON_CYCLE_CNT_reserved0_MASK        0xff000000
#define BCHP_DDR23_CTL_REGS_0_PMON_CYCLE_CNT_reserved0_SHIFT       24

/* DDR23_CTL_REGS_0 :: PMON_CYCLE_CNT :: count [23:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_CYCLE_CNT_count_MASK            0x00ffffff
#define BCHP_DDR23_CTL_REGS_0_PMON_CYCLE_CNT_count_SHIFT           0

/***************************************************************************
 *PMON_IDLE_CNT - Performance Monitoring Idle Cycles Count
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_IDLE_CNT :: reserved0 [31:24] */
#define BCHP_DDR23_CTL_REGS_0_PMON_IDLE_CNT_reserved0_MASK         0xff000000
#define BCHP_DDR23_CTL_REGS_0_PMON_IDLE_CNT_reserved0_SHIFT        24

/* DDR23_CTL_REGS_0 :: PMON_IDLE_CNT :: count [23:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_IDLE_CNT_count_MASK             0x00ffffff
#define BCHP_DDR23_CTL_REGS_0_PMON_IDLE_CNT_count_SHIFT            0

/***************************************************************************
 *PMON_RD_CNT1 - Performance Monitoring Data Channel #1 Read Accesses Count
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_RD_CNT1 :: reserved0 [31:24] */
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT1_reserved0_MASK          0xff000000
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT1_reserved0_SHIFT         24

/* DDR23_CTL_REGS_0 :: PMON_RD_CNT1 :: count [23:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT1_count_MASK              0x00ffffff
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT1_count_SHIFT             0

/***************************************************************************
 *PMON_RD_CNT2 - Performance Monitoring Data Channel #2 Read Accesses Count
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_RD_CNT2 :: reserved0 [31:24] */
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT2_reserved0_MASK          0xff000000
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT2_reserved0_SHIFT         24

/* DDR23_CTL_REGS_0 :: PMON_RD_CNT2 :: count [23:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT2_count_MASK              0x00ffffff
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT2_count_SHIFT             0

/***************************************************************************
 *PMON_RD_CNT3 - Performance Monitoring Data Channel #3 Read Accesses Count
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_RD_CNT3 :: reserved0 [31:24] */
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT3_reserved0_MASK          0xff000000
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT3_reserved0_SHIFT         24

/* DDR23_CTL_REGS_0 :: PMON_RD_CNT3 :: count [23:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT3_count_MASK              0x00ffffff
#define BCHP_DDR23_CTL_REGS_0_PMON_RD_CNT3_count_SHIFT             0

/***************************************************************************
 *PMON_WR_CNT1 - Performance Monitoring Data Channel #1 Write Accesses Count
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_WR_CNT1 :: reserved0 [31:24] */
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT1_reserved0_MASK          0xff000000
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT1_reserved0_SHIFT         24

/* DDR23_CTL_REGS_0 :: PMON_WR_CNT1 :: count [23:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT1_count_MASK              0x00ffffff
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT1_count_SHIFT             0

/***************************************************************************
 *PMON_WR_CNT2 - Performance Monitoring Data Channel #2 Write Accesses Count
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_WR_CNT2 :: reserved0 [31:24] */
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT2_reserved0_MASK          0xff000000
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT2_reserved0_SHIFT         24

/* DDR23_CTL_REGS_0 :: PMON_WR_CNT2 :: count [23:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT2_count_MASK              0x00ffffff
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT2_count_SHIFT             0

/***************************************************************************
 *PMON_WR_CNT3 - Performance Monitoring Data Channel #3 Write Accesses Count
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PMON_WR_CNT3 :: reserved0 [31:24] */
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT3_reserved0_MASK          0xff000000
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT3_reserved0_SHIFT         24

/* DDR23_CTL_REGS_0 :: PMON_WR_CNT3 :: count [23:00] */
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT3_count_MASK              0x00ffffff
#define BCHP_DDR23_CTL_REGS_0_PMON_WR_CNT3_count_SHIFT             0

/***************************************************************************
 *DDR_TM - RAM Macro TM Control
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: DDR_TM :: reserved0 [31:30] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_reserved0_MASK                0xc0000000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_reserved0_SHIFT               30

/* DDR23_CTL_REGS_0 :: DDR_TM :: prdb4 [29:28] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_prdb4_MASK                    0x30000000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_prdb4_SHIFT                   28

/* DDR23_CTL_REGS_0 :: DDR_TM :: prdb3 [27:26] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_prdb3_MASK                    0x0c000000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_prdb3_SHIFT                   26

/* DDR23_CTL_REGS_0 :: DDR_TM :: prdb2 [25:24] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_prdb2_MASK                    0x03000000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_prdb2_SHIFT                   24

/* DDR23_CTL_REGS_0 :: DDR_TM :: prdb1 [23:22] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_prdb1_MASK                    0x00c00000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_prdb1_SHIFT                   22

/* DDR23_CTL_REGS_0 :: DDR_TM :: sdc [21:20] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_sdc_MASK                      0x00300000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_sdc_SHIFT                     20

/* DDR23_CTL_REGS_0 :: DDR_TM :: row [19:18] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_row_MASK                      0x000c0000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_row_SHIFT                     18

/* DDR23_CTL_REGS_0 :: DDR_TM :: col [17:16] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_col_MASK                      0x00030000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_col_SHIFT                     16

/* DDR23_CTL_REGS_0 :: DDR_TM :: pic [15:14] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_pic_MASK                      0x0000c000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_pic_SHIFT                     14

/* DDR23_CTL_REGS_0 :: DDR_TM :: wrf3 [13:12] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_wrf3_MASK                     0x00003000
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_wrf3_SHIFT                    12

/* DDR23_CTL_REGS_0 :: DDR_TM :: wrf2 [11:10] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_wrf2_MASK                     0x00000c00
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_wrf2_SHIFT                    10

/* DDR23_CTL_REGS_0 :: DDR_TM :: wrf1 [09:08] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_wrf1_MASK                     0x00000300
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_wrf1_SHIFT                    8

/* DDR23_CTL_REGS_0 :: DDR_TM :: rdf3 [07:06] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_rdf3_MASK                     0x000000c0
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_rdf3_SHIFT                    6

/* DDR23_CTL_REGS_0 :: DDR_TM :: rdf2 [05:04] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_rdf2_MASK                     0x00000030
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_rdf2_SHIFT                    4

/* DDR23_CTL_REGS_0 :: DDR_TM :: rdf1_1 [03:02] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_rdf1_1_MASK                   0x0000000c
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_rdf1_1_SHIFT                  2

/* DDR23_CTL_REGS_0 :: DDR_TM :: rdf1_0 [01:00] */
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_rdf1_0_MASK                   0x00000003
#define BCHP_DDR23_CTL_REGS_0_DDR_TM_rdf1_0_SHIFT                  0

/***************************************************************************
 *PICT_BASE%i - Picture Buffer Base Address Ram
 ***************************************************************************/
#define BCHP_DDR23_CTL_REGS_0_PICT_BASEi_ARRAY_BASE                0x01800100
#define BCHP_DDR23_CTL_REGS_0_PICT_BASEi_ARRAY_START               0
#define BCHP_DDR23_CTL_REGS_0_PICT_BASEi_ARRAY_END                 63
#define BCHP_DDR23_CTL_REGS_0_PICT_BASEi_ARRAY_ELEMENT_SIZE        32

/***************************************************************************
 *PICT_BASE%i - Picture Buffer Base Address Ram
 ***************************************************************************/
/* DDR23_CTL_REGS_0 :: PICT_BASEi :: address [31:12] */
#define BCHP_DDR23_CTL_REGS_0_PICT_BASEi_address_MASK              0xfffff000
#define BCHP_DDR23_CTL_REGS_0_PICT_BASEi_address_SHIFT             12

/* DDR23_CTL_REGS_0 :: PICT_BASEi :: reserved0 [11:00] */
#define BCHP_DDR23_CTL_REGS_0_PICT_BASEi_reserved0_MASK            0x00000fff
#define BCHP_DDR23_CTL_REGS_0_PICT_BASEi_reserved0_SHIFT           0


#endif /* #ifndef BCHP_DDR23_CTL_REGS_0_H__ */

/* End of File */
