/***************************************************************************
 *     Copyright (c) 1999-2008, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_clk_vcxo.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 12/2/08 5:45p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Dec  2 13:58:15 2008
 *                 MD5 Checksum         90975bbcdf76045bb6bd092e6bdf481b
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7635/rdb/a0/bchp_clk_vcxo.h $
 * 
 * Hydra_Software_Devel/1   12/2/08 5:45p albertl
 * PR48688: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_CLK_VCXO_H__
#define BCHP_CLK_VCXO_H__

/***************************************************************************
 *CLK_VCXO - CLOCK_GEN_VCXO Registers
 ***************************************************************************/
#define BCHP_CLK_VCXO_MISC                       0x00040810 /* VCXO block output clock selection */

/***************************************************************************
 *MISC - VCXO block output clock selection
 ***************************************************************************/
/* CLK_VCXO :: MISC :: reserved0 [31:14] */
#define BCHP_CLK_VCXO_MISC_reserved0_MASK                          0xffffc000
#define BCHP_CLK_VCXO_MISC_reserved0_SHIFT                         14

/* CLK_VCXO :: MISC :: DIS_RAP0_DSP_PROG_CLK [13:13] */
#define BCHP_CLK_VCXO_MISC_DIS_RAP0_DSP_PROG_CLK_MASK              0x00002000
#define BCHP_CLK_VCXO_MISC_DIS_RAP0_DSP_PROG_CLK_SHIFT             13
#define BCHP_CLK_VCXO_MISC_DIS_RAP0_DSP_PROG_CLK_Enable            0
#define BCHP_CLK_VCXO_MISC_DIS_RAP0_DSP_PROG_CLK_Disable           1

/* CLK_VCXO :: MISC :: DIS_RAP1_DSP_PROG_CLK [12:12] */
#define BCHP_CLK_VCXO_MISC_DIS_RAP1_DSP_PROG_CLK_MASK              0x00001000
#define BCHP_CLK_VCXO_MISC_DIS_RAP1_DSP_PROG_CLK_SHIFT             12
#define BCHP_CLK_VCXO_MISC_DIS_RAP1_DSP_PROG_CLK_Enable            0
#define BCHP_CLK_VCXO_MISC_DIS_RAP1_DSP_PROG_CLK_Disable           1

/* CLK_VCXO :: MISC :: reserved1 [11:10] */
#define BCHP_CLK_VCXO_MISC_reserved1_MASK                          0x00000c00
#define BCHP_CLK_VCXO_MISC_reserved1_SHIFT                         10

/* CLK_VCXO :: MISC :: FORCE_NO_RAP_PLL_BYPASS [09:09] */
#define BCHP_CLK_VCXO_MISC_FORCE_NO_RAP_PLL_BYPASS_MASK            0x00000200
#define BCHP_CLK_VCXO_MISC_FORCE_NO_RAP_PLL_BYPASS_SHIFT           9

/* CLK_VCXO :: MISC :: reserved2 [08:00] */
#define BCHP_CLK_VCXO_MISC_reserved2_MASK                          0x000001ff
#define BCHP_CLK_VCXO_MISC_reserved2_SHIFT                         0

#endif /* #ifndef BCHP_CLK_VCXO_H__ */

/* End of File */
