/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_sata_cfg_1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 12/2/08 7:25p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Dec  2 13:59:50 2008
 *                 MD5 Checksum         90975bbcdf76045bb6bd092e6bdf481b
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7635/rdb/a0/bchp_sata_cfg_1.h $
 * 
 * Hydra_Software_Devel/1   12/2/08 7:25p albertl
 * PR48688: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_SATA_CFG_1_H__
#define BCHP_SATA_CFG_1_H__

/***************************************************************************
 *SATA_CFG_1 - PCIX Configuration Register 1
 ***************************************************************************/
#define BCHP_SATA_CFG_1_VENDOR_ID                0x5a0000 /* Vendor Identification Register */
#define BCHP_SATA_CFG_1_DEVICE_ID                0x5a0002 /* Device Identification Register */
#define BCHP_SATA_CFG_1_PCI_COMMAND              0x5a0004 /* PCI Command Register */
#define BCHP_SATA_CFG_1_PCI_STATUS               0x5a0006 /* PCI Status  Register */
#define BCHP_SATA_CFG_1_REV_ID_CLASS_CODE        0x005a0008 /* Class Code Register */
#define BCHP_SATA_CFG_1_CACHELINE_SIZE           0x5a000c /* Cacheline Size Register */
#define BCHP_SATA_CFG_1_MASTER_LATECY_TIMER      0x5a000d /* Master Latency Timer Register */
#define BCHP_SATA_CFG_1_HEADER_TYPE              0x5a000e /* Header Type Register */
#define BCHP_SATA_CFG_1_BIST                     0x5a000f /* Built-in Self Test (BIST) Register */
#define BCHP_SATA_CFG_1_PCS0                     0x005a0010 /* Base Address Register 0 (Primary CS0) */
#define BCHP_SATA_CFG_1_PCS1                     0x005a0014 /* Base Address Register 1 (Primary CS1) */
#define BCHP_SATA_CFG_1_SCS0                     0x005a0018 /* Base Address Register 2 (Secondary CS0) */
#define BCHP_SATA_CFG_1_SCS1                     0x005a001c /* Base Address Register 3 (Secondary CS1) */
#define BCHP_SATA_CFG_1_BUS_MASTER_BASE_ADDR     0x005a0020 /* Bus Master Interface Base Address Register */
#define BCHP_SATA_CFG_1_MMIO_BASE_ADDR           0x005a0024 /* MMIO Base Address Register */
#define BCHP_SATA_CFG_1_SUB_VENDOR_ID            0x5a002c /* Sub-System Vendor ID Register */
#define BCHP_SATA_CFG_1_SUB_DEVICE_ID            0x5a002e /* Sub-System Device ID Register */
#define BCHP_SATA_CFG_1_INTERRUPT_LINE           0x5a003c /* Interrupt Line Register */
#define BCHP_SATA_CFG_1_INTERRUPT_PIN            0x5a003d /* Interrupt Pin Register */
#define BCHP_SATA_CFG_1_MINIIMUM_GRANT           0x5a003e /* Minimum Grant Register */
#define BCHP_SATA_CFG_1_MAXIMUM_LATENCY          0x5a003f /* Maximum Latency Register */
#define BCHP_SATA_CFG_1_MISC_CONTROL             0x5a0070 /* SerialATA Misc Control Register */
#define BCHP_SATA_CFG_1_PCI_DEBUG_CONTROL        0x5a0078 /* SerialATA PCI Debug Control Register */
#define BCHP_SATA_CFG_1_GLOBAL_INTERRUPT_STATUS  0x005a0080 /* SerialATA Global Interrupt Status Register */

#endif /* #ifndef BCHP_SATA_CFG_1_H__ */

/* End of File */
