/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */
/* Host alias */
/* #undef CONFIG_STRING */


/* Name of package */
#define PACKAGE "TraceToolkit"

/* Version number of package */
#define VERSION "0.9.6pre2"

/* GNU/C compiler version */
/* #undef CC_VERSION */

