/***************************************************************************
 *     Copyright (c) 1999-2006, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * $brcm_Workfile: bchp_uartd.h $
 * $brcm_Revision: Hydra_Software_Devel/2 $
 * $brcm_Date: 4/19/06 11:27a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Mon Apr 17 15:58:09 2006
 *                 MD5 Checksum         91b8f8aff007e19e2e6981e74310b12e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.006
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7440/rdb/a0/bchp_uartd.h $
 * 
 * Hydra_Software_Devel/2   4/19/06 11:27a jasonh
 * PR 20907: RDB update.
 *
 ***************************************************************************/

#ifndef BCHP_UARTD_H__
#define BCHP_UARTD_H__

/***************************************************************************
 *UARTD - UART D
 ***************************************************************************/
#define BCHP_UARTD_RBR                           0x00400bc0 /* Receive Buffer Register */
#define BCHP_UARTD_THR                           0x00400bc0 /* Transmit Holding Register */
#define BCHP_UARTD_DLH                           0x00400bc4 /* Divisor Latch High */
#define BCHP_UARTD_DLL                           0x00400bc0 /* Divisor Latch Low */
#define BCHP_UARTD_IER                           0x00400bc4 /* Interrupt Enable Register */
#define BCHP_UARTD_IIR                           0x00400bc8 /* Interrupt Identity Register */
#define BCHP_UARTD_FCR                           0x00400bc8 /* FIFO Control Register */
#define BCHP_UARTD_LCR                           0x00400bcc /* Line Control Register */
#define BCHP_UARTD_MCR                           0x00400bd0 /* Modem Control Register */
#define BCHP_UARTD_LSR                           0x00400bd4 /* Line Status Register */
#define BCHP_UARTD_MSR                           0x00400bd8 /* Modem Status Register */
#define BCHP_UARTD_SCR                           0x00400bdc /* Scratchpad Register */

#endif /* #ifndef BCHP_UARTD_H__ */

/* End of File */
