/***************************************************************************
 *     Copyright (c) 1999-2007, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * $brcm_Workfile: bchp_sharf_mem_dma0.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 9/10/07 1:23p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Mon Sep 10 11:33:11 2007
 *                 MD5 Checksum         fb285bf6233707394ba42557465343cf
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008004
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7440/rdb/c0/bchp_sharf_mem_dma0.h $
 * 
 * Hydra_Software_Devel/1   9/10/07 1:23p tdo
 * PR34699: 7440C0: RDB to be checked into magnum
 *
 ***************************************************************************/

#ifndef BCHP_SHARF_MEM_DMA0_H__
#define BCHP_SHARF_MEM_DMA0_H__

/***************************************************************************
 *SHARF_MEM_DMA0 - SHARF_MEM_DMA Channel 0 Registers
 ***************************************************************************/
#define BCHP_SHARF_MEM_DMA0_FIRST_DESC           0x01b10100 /* SHARF_MEM_DMA First Descriptor Address Register */
#define BCHP_SHARF_MEM_DMA0_CTRL                 0x01b10104 /* SHARF_MEM_DMA Control Register */
#define BCHP_SHARF_MEM_DMA0_WAKE_CTRL            0x01b10108 /* SHARF_MEM_DMA Wake Control Register */
#define BCHP_SHARF_MEM_DMA0_STATUS               0x01b10110 /* SHARF_MEM_DMA Status Register */
#define BCHP_SHARF_MEM_DMA0_CUR_DESC             0x01b10114 /* SHARF_MEM_DMA  Current Descriptor Address Register */
#define BCHP_SHARF_MEM_DMA0_CUR_BYTE             0x01b10118 /* SHARF_MEM_DMA  Current Byte Count Register */
#define BCHP_SHARF_MEM_DMA0_SCRATCH              0x01b1011c /* SHARF_MEM_DMA Scratch Register */

/***************************************************************************
 *FIRST_DESC - SHARF_MEM_DMA First Descriptor Address Register
 ***************************************************************************/
/* SHARF_MEM_DMA0 :: FIRST_DESC :: ADDR [31:00] */
#define BCHP_SHARF_MEM_DMA0_FIRST_DESC_ADDR_MASK                   0xffffffff
#define BCHP_SHARF_MEM_DMA0_FIRST_DESC_ADDR_SHIFT                  0

/***************************************************************************
 *CTRL - SHARF_MEM_DMA Control Register
 ***************************************************************************/
/* SHARF_MEM_DMA0 :: CTRL :: reserved0 [31:01] */
#define BCHP_SHARF_MEM_DMA0_CTRL_reserved0_MASK                    0xfffffffe
#define BCHP_SHARF_MEM_DMA0_CTRL_reserved0_SHIFT                   1

/* SHARF_MEM_DMA0 :: CTRL :: RUN [00:00] */
#define BCHP_SHARF_MEM_DMA0_CTRL_RUN_MASK                          0x00000001
#define BCHP_SHARF_MEM_DMA0_CTRL_RUN_SHIFT                         0

/***************************************************************************
 *WAKE_CTRL - SHARF_MEM_DMA Wake Control Register
 ***************************************************************************/
/* SHARF_MEM_DMA0 :: WAKE_CTRL :: reserved0 [31:02] */
#define BCHP_SHARF_MEM_DMA0_WAKE_CTRL_reserved0_MASK               0xfffffffc
#define BCHP_SHARF_MEM_DMA0_WAKE_CTRL_reserved0_SHIFT              2

/* SHARF_MEM_DMA0 :: WAKE_CTRL :: WAKE_MODE [01:01] */
#define BCHP_SHARF_MEM_DMA0_WAKE_CTRL_WAKE_MODE_MASK               0x00000002
#define BCHP_SHARF_MEM_DMA0_WAKE_CTRL_WAKE_MODE_SHIFT              1

/* SHARF_MEM_DMA0 :: WAKE_CTRL :: WAKE [00:00] */
#define BCHP_SHARF_MEM_DMA0_WAKE_CTRL_WAKE_MASK                    0x00000001
#define BCHP_SHARF_MEM_DMA0_WAKE_CTRL_WAKE_SHIFT                   0

/***************************************************************************
 *STATUS - SHARF_MEM_DMA Status Register
 ***************************************************************************/
/* SHARF_MEM_DMA0 :: STATUS :: reserved0 [31:02] */
#define BCHP_SHARF_MEM_DMA0_STATUS_reserved0_MASK                  0xfffffffc
#define BCHP_SHARF_MEM_DMA0_STATUS_reserved0_SHIFT                 2

/* SHARF_MEM_DMA0 :: STATUS :: DMA_STATUS [01:00] */
#define BCHP_SHARF_MEM_DMA0_STATUS_DMA_STATUS_MASK                 0x00000003
#define BCHP_SHARF_MEM_DMA0_STATUS_DMA_STATUS_SHIFT                0
#define BCHP_SHARF_MEM_DMA0_STATUS_DMA_STATUS_Idle                 0
#define BCHP_SHARF_MEM_DMA0_STATUS_DMA_STATUS_Busy                 1
#define BCHP_SHARF_MEM_DMA0_STATUS_DMA_STATUS_Sleep                2
#define BCHP_SHARF_MEM_DMA0_STATUS_DMA_STATUS_Reserved             3

/***************************************************************************
 *CUR_DESC - SHARF_MEM_DMA  Current Descriptor Address Register
 ***************************************************************************/
/* SHARF_MEM_DMA0 :: CUR_DESC :: ADDR [31:00] */
#define BCHP_SHARF_MEM_DMA0_CUR_DESC_ADDR_MASK                     0xffffffff
#define BCHP_SHARF_MEM_DMA0_CUR_DESC_ADDR_SHIFT                    0

/***************************************************************************
 *CUR_BYTE - SHARF_MEM_DMA  Current Byte Count Register
 ***************************************************************************/
/* SHARF_MEM_DMA0 :: CUR_BYTE :: reserved0 [31:25] */
#define BCHP_SHARF_MEM_DMA0_CUR_BYTE_reserved0_MASK                0xfe000000
#define BCHP_SHARF_MEM_DMA0_CUR_BYTE_reserved0_SHIFT               25

/* SHARF_MEM_DMA0 :: CUR_BYTE :: COUNT [24:00] */
#define BCHP_SHARF_MEM_DMA0_CUR_BYTE_COUNT_MASK                    0x01ffffff
#define BCHP_SHARF_MEM_DMA0_CUR_BYTE_COUNT_SHIFT                   0

/***************************************************************************
 *SCRATCH - SHARF_MEM_DMA Scratch Register
 ***************************************************************************/
/* SHARF_MEM_DMA0 :: SCRATCH :: SCRATCH_BIT [31:00] */
#define BCHP_SHARF_MEM_DMA0_SCRATCH_SCRATCH_BIT_MASK               0xffffffff
#define BCHP_SHARF_MEM_DMA0_SCRATCH_SCRATCH_BIT_SHIFT              0

#endif /* #ifndef BCHP_SHARF_MEM_DMA0_H__ */

/* End of File */
