/***************************************************************************
 *     Copyright (c) 1999-2006, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_irq1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 2/10/06 5:53p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Feb 10 16:01:52 2006
 *                 MD5 Checksum         c4938591a1dffcbb175df566d9f5abc4
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.006
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7440/rdb/a0/bchp_irq1.h $
 * 
 * Hydra_Software_Devel/1   2/10/06 5:53p jasonh
 * PR 19602: Initial version.
 *
 ***************************************************************************/

#ifndef BCHP_IRQ1_H__
#define BCHP_IRQ1_H__

/***************************************************************************
 *IRQ1 - Level 2 PCI Interrupt Enable/Status
 ***************************************************************************/
#define BCHP_IRQ1_IRQEN                          0x00400788 /* Interrupt Enable */
#define BCHP_IRQ1_IRQSTAT                        0x0040078c /* Interrupt Status */

/***************************************************************************
 *IRQEN - Interrupt Enable
 ***************************************************************************/
/* IRQ1 :: IRQEN :: reserved_for_eco0 [31:26] */
#define BCHP_IRQ1_IRQEN_reserved_for_eco0_MASK                     0xfc000000
#define BCHP_IRQ1_IRQEN_reserved_for_eco0_SHIFT                    26

/* IRQ1 :: IRQEN :: iicb_irqen [25:25] */
#define BCHP_IRQ1_IRQEN_iicb_irqen_MASK                            0x02000000
#define BCHP_IRQ1_IRQEN_iicb_irqen_SHIFT                           25

/* IRQ1 :: IRQEN :: iica_irqen [24:24] */
#define BCHP_IRQ1_IRQEN_iica_irqen_MASK                            0x01000000
#define BCHP_IRQ1_IRQEN_iica_irqen_SHIFT                           24

/* IRQ1 :: IRQEN :: reserved_for_eco1 [23:21] */
#define BCHP_IRQ1_IRQEN_reserved_for_eco1_MASK                     0x00e00000
#define BCHP_IRQ1_IRQEN_reserved_for_eco1_SHIFT                    21

/* IRQ1 :: IRQEN :: spi_irqen [20:20] */
#define BCHP_IRQ1_IRQEN_spi_irqen_MASK                             0x00100000
#define BCHP_IRQ1_IRQEN_spi_irqen_SHIFT                            20

/* IRQ1 :: IRQEN :: reserved_for_eco2 [19:17] */
#define BCHP_IRQ1_IRQEN_reserved_for_eco2_MASK                     0x000e0000
#define BCHP_IRQ1_IRQEN_reserved_for_eco2_SHIFT                    17

/* IRQ1 :: IRQEN :: uarta_irqen [16:16] */
#define BCHP_IRQ1_IRQEN_uarta_irqen_MASK                           0x00010000
#define BCHP_IRQ1_IRQEN_uarta_irqen_SHIFT                          16

/* IRQ1 :: IRQEN :: reserved_for_eco3 [15:12] */
#define BCHP_IRQ1_IRQEN_reserved_for_eco3_MASK                     0x0000f000
#define BCHP_IRQ1_IRQEN_reserved_for_eco3_SHIFT                    12

/* IRQ1 :: IRQEN :: ud_irqen [11:11] */
#define BCHP_IRQ1_IRQEN_ud_irqen_MASK                              0x00000800
#define BCHP_IRQ1_IRQEN_ud_irqen_SHIFT                             11

/* IRQ1 :: IRQEN :: reserved_for_eco4 [10:10] */
#define BCHP_IRQ1_IRQEN_reserved_for_eco4_MASK                     0x00000400
#define BCHP_IRQ1_IRQEN_reserved_for_eco4_SHIFT                    10

/* IRQ1 :: IRQEN :: uc_irqen [09:09] */
#define BCHP_IRQ1_IRQEN_uc_irqen_MASK                              0x00000200
#define BCHP_IRQ1_IRQEN_uc_irqen_SHIFT                             9

/* IRQ1 :: IRQEN :: reserved_for_eco5 [08:08] */
#define BCHP_IRQ1_IRQEN_reserved_for_eco5_MASK                     0x00000100
#define BCHP_IRQ1_IRQEN_reserved_for_eco5_SHIFT                    8

/* IRQ1 :: IRQEN :: icap_irqen [07:07] */
#define BCHP_IRQ1_IRQEN_icap_irqen_MASK                            0x00000080
#define BCHP_IRQ1_IRQEN_icap_irqen_SHIFT                           7

/* IRQ1 :: IRQEN :: gio_irqen [06:06] */
#define BCHP_IRQ1_IRQEN_gio_irqen_MASK                             0x00000040
#define BCHP_IRQ1_IRQEN_gio_irqen_SHIFT                            6

/* IRQ1 :: IRQEN :: reserved_for_eco6 [05:05] */
#define BCHP_IRQ1_IRQEN_reserved_for_eco6_MASK                     0x00000020
#define BCHP_IRQ1_IRQEN_reserved_for_eco6_SHIFT                    5

/* IRQ1 :: IRQEN :: ua_irqen [04:04] */
#define BCHP_IRQ1_IRQEN_ua_irqen_MASK                              0x00000010
#define BCHP_IRQ1_IRQEN_ua_irqen_SHIFT                             4

/* IRQ1 :: IRQEN :: ub_irqen [03:03] */
#define BCHP_IRQ1_IRQEN_ub_irqen_MASK                              0x00000008
#define BCHP_IRQ1_IRQEN_ub_irqen_SHIFT                             3

/* IRQ1 :: IRQEN :: reserved_for_eco7 [02:02] */
#define BCHP_IRQ1_IRQEN_reserved_for_eco7_MASK                     0x00000004
#define BCHP_IRQ1_IRQEN_reserved_for_eco7_SHIFT                    2

/* IRQ1 :: IRQEN :: ldk_irqen [01:01] */
#define BCHP_IRQ1_IRQEN_ldk_irqen_MASK                             0x00000002
#define BCHP_IRQ1_IRQEN_ldk_irqen_SHIFT                            1

/* IRQ1 :: IRQEN :: kbd1_irqen [00:00] */
#define BCHP_IRQ1_IRQEN_kbd1_irqen_MASK                            0x00000001
#define BCHP_IRQ1_IRQEN_kbd1_irqen_SHIFT                           0

/***************************************************************************
 *IRQSTAT - Interrupt Status
 ***************************************************************************/
/* IRQ1 :: IRQSTAT :: reserved0 [31:26] */
#define BCHP_IRQ1_IRQSTAT_reserved0_MASK                           0xfc000000
#define BCHP_IRQ1_IRQSTAT_reserved0_SHIFT                          26

/* IRQ1 :: IRQSTAT :: iicbirq [25:25] */
#define BCHP_IRQ1_IRQSTAT_iicbirq_MASK                             0x02000000
#define BCHP_IRQ1_IRQSTAT_iicbirq_SHIFT                            25

/* IRQ1 :: IRQSTAT :: iicairq [24:24] */
#define BCHP_IRQ1_IRQSTAT_iicairq_MASK                             0x01000000
#define BCHP_IRQ1_IRQSTAT_iicairq_SHIFT                            24

/* IRQ1 :: IRQSTAT :: reserved1 [23:21] */
#define BCHP_IRQ1_IRQSTAT_reserved1_MASK                           0x00e00000
#define BCHP_IRQ1_IRQSTAT_reserved1_SHIFT                          21

/* IRQ1 :: IRQSTAT :: spiirq [20:20] */
#define BCHP_IRQ1_IRQSTAT_spiirq_MASK                              0x00100000
#define BCHP_IRQ1_IRQSTAT_spiirq_SHIFT                             20

/* IRQ1 :: IRQSTAT :: reserved2 [19:17] */
#define BCHP_IRQ1_IRQSTAT_reserved2_MASK                           0x000e0000
#define BCHP_IRQ1_IRQSTAT_reserved2_SHIFT                          17

/* IRQ1 :: IRQSTAT :: uarta_irq [16:16] */
#define BCHP_IRQ1_IRQSTAT_uarta_irq_MASK                           0x00010000
#define BCHP_IRQ1_IRQSTAT_uarta_irq_SHIFT                          16

/* IRQ1 :: IRQSTAT :: reserved3 [15:12] */
#define BCHP_IRQ1_IRQSTAT_reserved3_MASK                           0x0000f000
#define BCHP_IRQ1_IRQSTAT_reserved3_SHIFT                          12

/* IRQ1 :: IRQSTAT :: udirq [11:11] */
#define BCHP_IRQ1_IRQSTAT_udirq_MASK                               0x00000800
#define BCHP_IRQ1_IRQSTAT_udirq_SHIFT                              11

/* IRQ1 :: IRQSTAT :: reserved4 [10:10] */
#define BCHP_IRQ1_IRQSTAT_reserved4_MASK                           0x00000400
#define BCHP_IRQ1_IRQSTAT_reserved4_SHIFT                          10

/* IRQ1 :: IRQSTAT :: ucirq [09:09] */
#define BCHP_IRQ1_IRQSTAT_ucirq_MASK                               0x00000200
#define BCHP_IRQ1_IRQSTAT_ucirq_SHIFT                              9

/* IRQ1 :: IRQSTAT :: reserved5 [08:08] */
#define BCHP_IRQ1_IRQSTAT_reserved5_MASK                           0x00000100
#define BCHP_IRQ1_IRQSTAT_reserved5_SHIFT                          8

/* IRQ1 :: IRQSTAT :: icapirq [07:07] */
#define BCHP_IRQ1_IRQSTAT_icapirq_MASK                             0x00000080
#define BCHP_IRQ1_IRQSTAT_icapirq_SHIFT                            7

/* IRQ1 :: IRQSTAT :: gioirq [06:06] */
#define BCHP_IRQ1_IRQSTAT_gioirq_MASK                              0x00000040
#define BCHP_IRQ1_IRQSTAT_gioirq_SHIFT                             6

/* IRQ1 :: IRQSTAT :: reserved6 [05:05] */
#define BCHP_IRQ1_IRQSTAT_reserved6_MASK                           0x00000020
#define BCHP_IRQ1_IRQSTAT_reserved6_SHIFT                          5

/* IRQ1 :: IRQSTAT :: uairq [04:04] */
#define BCHP_IRQ1_IRQSTAT_uairq_MASK                               0x00000010
#define BCHP_IRQ1_IRQSTAT_uairq_SHIFT                              4

/* IRQ1 :: IRQSTAT :: ubirq [03:03] */
#define BCHP_IRQ1_IRQSTAT_ubirq_MASK                               0x00000008
#define BCHP_IRQ1_IRQSTAT_ubirq_SHIFT                              3

/* IRQ1 :: IRQSTAT :: reserved7 [02:02] */
#define BCHP_IRQ1_IRQSTAT_reserved7_MASK                           0x00000004
#define BCHP_IRQ1_IRQSTAT_reserved7_SHIFT                          2

/* IRQ1 :: IRQSTAT :: ldkirq [01:01] */
#define BCHP_IRQ1_IRQSTAT_ldkirq_MASK                              0x00000002
#define BCHP_IRQ1_IRQSTAT_ldkirq_SHIFT                             1

/* IRQ1 :: IRQSTAT :: kbd1irq [00:00] */
#define BCHP_IRQ1_IRQSTAT_kbd1irq_MASK                             0x00000001
#define BCHP_IRQ1_IRQSTAT_kbd1irq_SHIFT                            0

#endif /* #ifndef BCHP_IRQ1_H__ */

/* End of File */
