#
# This is makefile used by Broadcom's Reference Linux distribution to copy proper files from this package into rootfs on target
#
# History:
# Oct 8, 2007	Jian Peng - initial version
#

romfs: install

install: Makefile.brcm
	make -f Makefile.brcm install
