# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../..

prefix = /home/sjhill/uClinux-dist-patched/romfs
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/DirectFB
pkglibdir = $(libdir)/DirectFB
pkgincludedir = $(includedir)/DirectFB

top_builddir = ../..

ACLOCAL = /home/sjhill/uClinux-dist-patched/lib/directfb/missing aclocal-1.4 
AUTOCONF = autoconf
AUTOMAKE = /home/sjhill/uClinux-dist-patched/lib/directfb/missing automake-1.4
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = mipsel-linux
host_triplet = mipsel-unknown-linux-gnu
AS = mipsel-linux-as
ASFLAGS = 
AVIFILE_CFLAGS = 
AVIFILE_CONFIG = 
AVIFILE_LIBS = 
AVIFILE_PROVIDER = 
CC = mipsel-linux-gcc -L/home/sjhill/uClinux-dist-patched/romfs/lib -I/home/sjhill/uClinux-dist-patched/romfs/include -lm
CXX = mipsel-linux-g++
DATADIR = ${prefix}/share/directfb-0.9.13
DFB_CFLAGS = -D_REENTRANT -ffast-math -Wall -O3  -DFUSION_FAKE
DFB_CFLAGS_OMIT_FRAME_POINTER = -fomit-frame-pointer
DFB_CXXFLAGS = -D_REENTRANT -ffast-math -Wall -O3  -DFUSION_FAKE
DFB_INTERNAL_CFLAGS =  -DFUSION_FAKE
DFB_LDFLAGS = -O2 -g -fno-builtin -I/home/sjhill/uClinux-dist-patched/lib/uClibc/include -I/home/sjhill/uClinux-dist-patched -Dlinux -D__linux__ -D__uClinux__ -Dunix -DEMBED -I/home/sjhill/uClinux-dist-patched/linux-2.4.x/include
DIRECTFB_BINARY_AGE = 0
DIRECTFB_INTERFACE_AGE = 0
DIRECTFB_MAJOR_VERSION = 0
DIRECTFB_MICRO_VERSION = 13
DIRECTFB_MINOR_VERSION = 9
DIRECTFB_VERSION = 0.9.13
DLLTOOL = @DLLTOOL@
ECHO = echo
EXEEXT = 
FREETYPE_CFLAGS = 
FREETYPE_CONFIG = no
FREETYPE_LIBS = 
FREETYPE_PROVIDER = 
GFX_ATI = 
GFX_MATROX = 
GFX_TDFX = 
GIF_PROVIDER = 
INCLUDEDIR = ${prefix}/include/directfb
INTERNALINCLUDEDIR = ${prefix}/include/directfb-internal
JPEG_PROVIDER = 
LIBFLASH = 
LIBJPEG = 
LIBMPEG3 = 
LIBPNG = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBZ = 
LN_S = ln -s
LT_AGE = 0
LT_CURRENT = 13
LT_RELEASE = 0.9
LT_REVISION = 0
MAINT = #
MAKEINFO = makeinfo
MODULEDIR = ${exec_prefix}/lib/directfb-0.9.13
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = DirectFB
PERL = /usr/bin/perl
PNG_PROVIDER = 
RANLIB = mipsel-linux-ranlib
SOPATH = ${exec_prefix}/lib/libdirectfb-0.9.so.13
STRIP = mipsel-linux-strip
VERSION = 0.9.13

idirectfbfontdir = $(MODULEDIR)/interfaces/IDirectFBFont
#FREETYPE_PROVIDER_LTLIB = libidirectfbfont_ft2.la
FREETYPE_PROVIDER_LTLIB = 

INCLUDES =  	-I$(top_srcdir)/include		-I$(top_srcdir)/src 		-DDATADIR=\"${prefix}/share/directfb-0.9.13\"


CFLAGS = $(DFB_CFLAGS) $(FREETYPE_CFLAGS)

idirectfbfont_LTLIBRARIES =  	libidirectfbfont_default.la		$(FREETYPE_PROVIDER_LTLIB)


libidirectfbfont_default_la_SOURCES = idirectfbfont_default.c

libidirectfbfont_default_la_LDFLAGS = -avoid-version -module

libidirectfbfont_ft2_la_SOURCES = idirectfbfont_ft2.c

libidirectfbfont_ft2_la_LIBADD = $(FREETYPE_LIBS)

libidirectfbfont_ft2_la_LDFLAGS = -avoid-version -module
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(idirectfbfont_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../..
CPPFLAGS = 
LDFLAGS = -O2 -g -fno-builtin -I/home/sjhill/uClinux-dist-patched/lib/uClibc/include -I/home/sjhill/uClinux-dist-patched -Dlinux -D__linux__ -D__uClinux__ -Dunix -DEMBED -I/home/sjhill/uClinux-dist-patched/linux-2.4.x/include
LIBS = -ldl -lpthread 
libidirectfbfont_default_la_LIBADD = 
libidirectfbfont_default_la_OBJECTS =  idirectfbfont_default.lo
libidirectfbfont_ft2_la_DEPENDENCIES = 
libidirectfbfont_ft2_la_OBJECTS =  idirectfbfont_ft2.lo
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
SOURCES = $(libidirectfbfont_default_la_SOURCES) $(libidirectfbfont_ft2_la_SOURCES)
OBJECTS = $(libidirectfbfont_default_la_OBJECTS) $(libidirectfbfont_ft2_la_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps interfaces/IDirectFBFont/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-idirectfbfontLTLIBRARIES:

clean-idirectfbfontLTLIBRARIES:
	-test -z "$(idirectfbfont_LTLIBRARIES)" || rm -f $(idirectfbfont_LTLIBRARIES)

distclean-idirectfbfontLTLIBRARIES:

maintainer-clean-idirectfbfontLTLIBRARIES:

install-idirectfbfontLTLIBRARIES: $(idirectfbfont_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(idirectfbfontdir)
	@list='$(idirectfbfont_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(idirectfbfontdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(idirectfbfontdir)/$$p; \
	  else :; fi; \
	done

uninstall-idirectfbfontLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(idirectfbfont_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(idirectfbfontdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libidirectfbfont_default.la: $(libidirectfbfont_default_la_OBJECTS) $(libidirectfbfont_default_la_DEPENDENCIES)
	$(LINK) -rpath $(idirectfbfontdir) $(libidirectfbfont_default_la_LDFLAGS) $(libidirectfbfont_default_la_OBJECTS) $(libidirectfbfont_default_la_LIBADD) $(LIBS)

libidirectfbfont_ft2.la: $(libidirectfbfont_ft2_la_OBJECTS) $(libidirectfbfont_ft2_la_DEPENDENCIES)
	$(LINK) -rpath $(idirectfbfontdir) $(libidirectfbfont_ft2_la_LDFLAGS) $(libidirectfbfont_ft2_la_OBJECTS) $(libidirectfbfont_ft2_la_LIBADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags -o $$here/TAGS $(ETAGS_ARGS) $$tags  $$unique $(LISP))

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = interfaces/IDirectFBFont

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
idirectfbfont_default.lo idirectfbfont_default.o : \
	idirectfbfont_default.c ../../include/directfb.h \
	../../include/directfb_keyboard.h ../../src/core/fonts.h \
	../../src/core/fusion/lock.h \
	../../src/core/fusion/fusion_types.h ../../src/core/coretypes.h \
	../../src/core/state.h ../../src/core/gfxcard.h \
	../../src/core/surfaces.h ../../src/core/fusion/object.h \
	../../src/core/fusion/list.h ../../src/core/fusion/ref.h \
	../../src/core/fusion/reactor.h ../../src/core/surfacemanager.h \
	../../src/core/core.h ../../src/core/coredefs.h ../../config.h \
	../../src/misc/conf.h ../../src/misc/util.h \
	../../src/gfx/convert.h ../../src/misc/memcpy.h \
	../../src/media/idirectfbfont.h ../../src/misc/tree.h \
	../../src/misc/utf8.h ../../src/misc/mem.h \
	../../src/interface_implementation.h ../../src/core/input.h \
	../../include/directfb_internals.h
idirectfbfont_ft2.lo idirectfbfont_ft2.o : idirectfbfont_ft2.c \
	../../include/directfb.h ../../include/directfb_keyboard.h \
	../../src/core/fonts.h ../../src/core/fusion/lock.h \
	../../src/core/fusion/fusion_types.h ../../src/core/coretypes.h \
	../../src/core/state.h ../../src/core/gfxcard.h \
	../../src/core/surfaces.h ../../src/core/fusion/object.h \
	../../src/core/fusion/list.h ../../src/core/fusion/ref.h \
	../../src/core/fusion/reactor.h ../../src/core/surfacemanager.h \
	../../src/core/core.h ../../src/core/coredefs.h ../../config.h \
	../../src/misc/conf.h ../../src/misc/util.h \
	../../src/gfx/convert.h ../../src/misc/memcpy.h \
	../../src/media/idirectfbfont.h ../../src/misc/tree.h \
	../../src/misc/mem.h ../../src/interface_implementation.h \
	../../src/core/input.h ../../include/directfb_internals.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-idirectfbfontLTLIBRARIES
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-idirectfbfontLTLIBRARIES
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(idirectfbfontdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-idirectfbfontLTLIBRARIES \
		mostlyclean-compile mostlyclean-libtool \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-idirectfbfontLTLIBRARIES clean-compile clean-libtool \
		clean-tags clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-idirectfbfontLTLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-idirectfbfontLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-idirectfbfontLTLIBRARIES \
distclean-idirectfbfontLTLIBRARIES clean-idirectfbfontLTLIBRARIES \
maintainer-clean-idirectfbfontLTLIBRARIES \
uninstall-idirectfbfontLTLIBRARIES install-idirectfbfontLTLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
