/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_vide_ctl.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 5/14/09 2:06a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed May 13 17:36:01 2009
 *                 MD5 Checksum         397c7e3e68fca5836958d6d3dcfe31f9
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7630/rdb/b0/bchp_vide_ctl.h $
 * 
 * Hydra_Software_Devel/1   5/14/09 2:06a tdo
 * PR55087: Initial check in
 *
 ***************************************************************************/

#ifndef BCHP_VIDE_CTL_H__
#define BCHP_VIDE_CTL_H__

/***************************************************************************
 *VIDE_CTL
 ***************************************************************************/
#define BCHP_VIDE_CTL_REG                        0x00290500 /* Control Register */
#define BCHP_VIDE_CTL_STATUS                     0x00290504 /* Status Register */
#define BCHP_VIDE_CTL_VERSION                    0x00290508 /* Version Register */
#define BCHP_VIDE_CTL_SPARE                      0x0029050c /* Spare Register */
#define BCHP_VIDE_CTL_DIAG1                      0x00290510 /* Diagnostic Register */

/***************************************************************************
 *REG - Control Register
 ***************************************************************************/
/* VIDE_CTL :: REG :: SysEnd [31:31] */
#define BCHP_VIDE_CTL_REG_SysEnd_MASK                              0x80000000
#define BCHP_VIDE_CTL_REG_SysEnd_SHIFT                             31

/* VIDE_CTL :: REG :: reserved0 [30:22] */
#define BCHP_VIDE_CTL_REG_reserved0_MASK                           0x7fc00000
#define BCHP_VIDE_CTL_REG_reserved0_SHIFT                          22

/* VIDE_CTL :: REG :: DataWait [21:16] */
#define BCHP_VIDE_CTL_REG_DataWait_MASK                            0x003f0000
#define BCHP_VIDE_CTL_REG_DataWait_SHIFT                           16

/* VIDE_CTL :: REG :: reserved1 [15:05] */
#define BCHP_VIDE_CTL_REG_reserved1_MASK                           0x0000ffe0
#define BCHP_VIDE_CTL_REG_reserved1_SHIFT                          5

/* VIDE_CTL :: REG :: SoftRst [04:04] */
#define BCHP_VIDE_CTL_REG_SoftRst_MASK                             0x00000010
#define BCHP_VIDE_CTL_REG_SoftRst_SHIFT                            4

/* VIDE_CTL :: REG :: SwapData [03:03] */
#define BCHP_VIDE_CTL_REG_SwapData_MASK                            0x00000008
#define BCHP_VIDE_CTL_REG_SwapData_SHIFT                           3

/* VIDE_CTL :: REG :: DmaWordSwap [02:02] */
#define BCHP_VIDE_CTL_REG_DmaWordSwap_MASK                         0x00000004
#define BCHP_VIDE_CTL_REG_DmaWordSwap_SHIFT                        2

/* VIDE_CTL :: REG :: DmaByteSwap [01:01] */
#define BCHP_VIDE_CTL_REG_DmaByteSwap_MASK                         0x00000002
#define BCHP_VIDE_CTL_REG_DmaByteSwap_SHIFT                        1

/* VIDE_CTL :: REG :: BigEndian [00:00] */
#define BCHP_VIDE_CTL_REG_BigEndian_MASK                           0x00000001
#define BCHP_VIDE_CTL_REG_BigEndian_SHIFT                          0

/***************************************************************************
 *STATUS - Status Register
 ***************************************************************************/
/* VIDE_CTL :: STATUS :: reserved0 [31:01] */
#define BCHP_VIDE_CTL_STATUS_reserved0_MASK                        0xfffffffe
#define BCHP_VIDE_CTL_STATUS_reserved0_SHIFT                       1

/* VIDE_CTL :: STATUS :: ResetDone [00:00] */
#define BCHP_VIDE_CTL_STATUS_ResetDone_MASK                        0x00000001
#define BCHP_VIDE_CTL_STATUS_ResetDone_SHIFT                       0

/***************************************************************************
 *VERSION - Version Register
 ***************************************************************************/
/* VIDE_CTL :: VERSION :: reserved0 [31:24] */
#define BCHP_VIDE_CTL_VERSION_reserved0_MASK                       0xff000000
#define BCHP_VIDE_CTL_VERSION_reserved0_SHIFT                      24

/* VIDE_CTL :: VERSION :: Major [23:16] */
#define BCHP_VIDE_CTL_VERSION_Major_MASK                           0x00ff0000
#define BCHP_VIDE_CTL_VERSION_Major_SHIFT                          16

/* VIDE_CTL :: VERSION :: Minor [15:08] */
#define BCHP_VIDE_CTL_VERSION_Minor_MASK                           0x0000ff00
#define BCHP_VIDE_CTL_VERSION_Minor_SHIFT                          8

/* VIDE_CTL :: VERSION :: Mask [07:00] */
#define BCHP_VIDE_CTL_VERSION_Mask_MASK                            0x000000ff
#define BCHP_VIDE_CTL_VERSION_Mask_SHIFT                           0

/***************************************************************************
 *SPARE - Spare Register
 ***************************************************************************/
/* VIDE_CTL :: SPARE :: Spare [31:00] */
#define BCHP_VIDE_CTL_SPARE_Spare_MASK                             0xffffffff
#define BCHP_VIDE_CTL_SPARE_Spare_SHIFT                            0

/***************************************************************************
 *DIAG1 - Diagnostic Register
 ***************************************************************************/
/* VIDE_CTL :: DIAG1 :: reserved0 [31:01] */
#define BCHP_VIDE_CTL_DIAG1_reserved0_MASK                         0xfffffffe
#define BCHP_VIDE_CTL_DIAG1_reserved0_SHIFT                        1

/* VIDE_CTL :: DIAG1 :: HostReqActive [00:00] */
#define BCHP_VIDE_CTL_DIAG1_HostReqActive_MASK                     0x00000001
#define BCHP_VIDE_CTL_DIAG1_HostReqActive_SHIFT                    0

#endif /* #ifndef BCHP_VIDE_CTL_H__ */

/* End of File */
