/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_art.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 5/14/09 12:19a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed May 13 17:31:59 2009
 *                 MD5 Checksum         397c7e3e68fca5836958d6d3dcfe31f9
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7630/rdb/b0/bchp_art.h $
 * 
 * Hydra_Software_Devel/1   5/14/09 12:19a tdo
 * PR55087: Initial check in
 *
 ***************************************************************************/

#ifndef BCHP_ART_H__
#define BCHP_ART_H__

/***************************************************************************
 *ART - Power Management Control "Autonomous Register Transfers" Registers
 ***************************************************************************/
#define BCHP_ART_REVISION                        0x00071000 /* Autonomous Register Transfer (ART) Revision ID */
#define BCHP_ART_CONFIG                          0x00071004 /* Various Configuration Settings */
#define BCHP_ART_STATUS                          0x00071008 /* General Hardware Status */
#define BCHP_ART_WAKEUP_CONTROL                  0x00071010 /* ART Wakeup Event Control */
#define BCHP_ART_SLEEP_CONTROL                   0x00071014 /* ART Sleep Event Control */
#define BCHP_ART_SEQUENCE_TRIGGER                0x00071018 /* ART Sequence Trigger Manual Control */
#define BCHP_ART_SEQUENCE_STATUS                 0x0007101c /* ART Sequencer Status */
#define BCHP_ART_CODESTORE_POINTER               0x00071020 /* Address for Access to Code Store Memory */
#define BCHP_ART_CODESTORE_DATA                  0x00071024 /* Data Word for Access to Code Store Memory */
#define BCHP_ART_CODESTORE_TM                    0x00071028 /* Code Store Memory Test Mode Control */
#define BCHP_ART_DEBUG                           0x0007102c /* ART Debug Output */

/***************************************************************************
 *REVISION - Autonomous Register Transfer (ART) Revision ID
 ***************************************************************************/
/* ART :: REVISION :: reserved0 [31:24] */
#define BCHP_ART_REVISION_reserved0_MASK                           0xff000000
#define BCHP_ART_REVISION_reserved0_SHIFT                          24

/* ART :: REVISION :: MAJOR [23:16] */
#define BCHP_ART_REVISION_MAJOR_MASK                               0x00ff0000
#define BCHP_ART_REVISION_MAJOR_SHIFT                              16

/* ART :: REVISION :: MINOR [15:08] */
#define BCHP_ART_REVISION_MINOR_MASK                               0x0000ff00
#define BCHP_ART_REVISION_MINOR_SHIFT                              8

/* ART :: REVISION :: METAL [07:00] */
#define BCHP_ART_REVISION_METAL_MASK                               0x000000ff
#define BCHP_ART_REVISION_METAL_SHIFT                              0

/***************************************************************************
 *CONFIG - Various Configuration Settings
 ***************************************************************************/
/* ART :: CONFIG :: reserved_for_eco0 [31:16] */
#define BCHP_ART_CONFIG_reserved_for_eco0_MASK                     0xffff0000
#define BCHP_ART_CONFIG_reserved_for_eco0_SHIFT                    16

/* ART :: CONFIG :: RBUS_BACKOFF [15:00] */
#define BCHP_ART_CONFIG_RBUS_BACKOFF_MASK                          0x0000ffff
#define BCHP_ART_CONFIG_RBUS_BACKOFF_SHIFT                         0

/***************************************************************************
 *STATUS - General Hardware Status
 ***************************************************************************/
/* ART :: STATUS :: reserved0 [31:19] */
#define BCHP_ART_STATUS_reserved0_MASK                             0xfff80000
#define BCHP_ART_STATUS_reserved0_SHIFT                            19

/* ART :: STATUS :: AEGIS_RDY [18:18] */
#define BCHP_ART_STATUS_AEGIS_RDY_MASK                             0x00040000
#define BCHP_ART_STATUS_AEGIS_RDY_SHIFT                            18

/* ART :: STATUS :: DDR1_ACTIVE [17:17] */
#define BCHP_ART_STATUS_DDR1_ACTIVE_MASK                           0x00020000
#define BCHP_ART_STATUS_DDR1_ACTIVE_SHIFT                          17

/* ART :: STATUS :: DDR0_ACTIVE [16:16] */
#define BCHP_ART_STATUS_DDR0_ACTIVE_MASK                           0x00010000
#define BCHP_ART_STATUS_DDR0_ACTIVE_SHIFT                          16

/* ART :: STATUS :: reserved1 [15:00] */
#define BCHP_ART_STATUS_reserved1_MASK                             0x0000ffff
#define BCHP_ART_STATUS_reserved1_SHIFT                            0

/***************************************************************************
 *WAKEUP_CONTROL - ART Wakeup Event Control
 ***************************************************************************/
/* ART :: WAKEUP_CONTROL :: ENABLE_WAKEUP [31:31] */
#define BCHP_ART_WAKEUP_CONTROL_ENABLE_WAKEUP_MASK                 0x80000000
#define BCHP_ART_WAKEUP_CONTROL_ENABLE_WAKEUP_SHIFT                31

/* ART :: WAKEUP_CONTROL :: reserved_for_eco0 [30:08] */
#define BCHP_ART_WAKEUP_CONTROL_reserved_for_eco0_MASK             0x7fffff00
#define BCHP_ART_WAKEUP_CONTROL_reserved_for_eco0_SHIFT            8

/* ART :: WAKEUP_CONTROL :: WAKEUP_POINTER [07:00] */
#define BCHP_ART_WAKEUP_CONTROL_WAKEUP_POINTER_MASK                0x000000ff
#define BCHP_ART_WAKEUP_CONTROL_WAKEUP_POINTER_SHIFT               0

/***************************************************************************
 *SLEEP_CONTROL - ART Sleep Event Control
 ***************************************************************************/
/* ART :: SLEEP_CONTROL :: ENABLE_SLEEP [31:31] */
#define BCHP_ART_SLEEP_CONTROL_ENABLE_SLEEP_MASK                   0x80000000
#define BCHP_ART_SLEEP_CONTROL_ENABLE_SLEEP_SHIFT                  31

/* ART :: SLEEP_CONTROL :: reserved_for_eco0 [30:08] */
#define BCHP_ART_SLEEP_CONTROL_reserved_for_eco0_MASK              0x7fffff00
#define BCHP_ART_SLEEP_CONTROL_reserved_for_eco0_SHIFT             8

/* ART :: SLEEP_CONTROL :: SLEEP_POINTER [07:00] */
#define BCHP_ART_SLEEP_CONTROL_SLEEP_POINTER_MASK                  0x000000ff
#define BCHP_ART_SLEEP_CONTROL_SLEEP_POINTER_SHIFT                 0

/***************************************************************************
 *SEQUENCE_TRIGGER - ART Sequence Trigger Manual Control
 ***************************************************************************/
/* ART :: SEQUENCE_TRIGGER :: reserved0 [31:03] */
#define BCHP_ART_SEQUENCE_TRIGGER_reserved0_MASK                   0xfffffff8
#define BCHP_ART_SEQUENCE_TRIGGER_reserved0_SHIFT                  3

/* ART :: SEQUENCE_TRIGGER :: SEQ_STOP [02:02] */
#define BCHP_ART_SEQUENCE_TRIGGER_SEQ_STOP_MASK                    0x00000004
#define BCHP_ART_SEQUENCE_TRIGGER_SEQ_STOP_SHIFT                   2

/* ART :: SEQUENCE_TRIGGER :: WAKEUP_START [01:01] */
#define BCHP_ART_SEQUENCE_TRIGGER_WAKEUP_START_MASK                0x00000002
#define BCHP_ART_SEQUENCE_TRIGGER_WAKEUP_START_SHIFT               1

/* ART :: SEQUENCE_TRIGGER :: SLEEP_START [00:00] */
#define BCHP_ART_SEQUENCE_TRIGGER_SLEEP_START_MASK                 0x00000001
#define BCHP_ART_SEQUENCE_TRIGGER_SLEEP_START_SHIFT                0

/***************************************************************************
 *SEQUENCE_STATUS - ART Sequencer Status
 ***************************************************************************/
/* ART :: SEQUENCE_STATUS :: ART_STATE [31:28] */
#define BCHP_ART_SEQUENCE_STATUS_ART_STATE_MASK                    0xf0000000
#define BCHP_ART_SEQUENCE_STATUS_ART_STATE_SHIFT                   28

/* ART :: SEQUENCE_STATUS :: reserved0 [27:23] */
#define BCHP_ART_SEQUENCE_STATUS_reserved0_MASK                    0x0f800000
#define BCHP_ART_SEQUENCE_STATUS_reserved0_SHIFT                   23

/* ART :: SEQUENCE_STATUS :: RBUS_ERR_ACK [22:22] */
#define BCHP_ART_SEQUENCE_STATUS_RBUS_ERR_ACK_MASK                 0x00400000
#define BCHP_ART_SEQUENCE_STATUS_RBUS_ERR_ACK_SHIFT                22

/* ART :: SEQUENCE_STATUS :: BAD_OPCODE [21:21] */
#define BCHP_ART_SEQUENCE_STATUS_BAD_OPCODE_MASK                   0x00200000
#define BCHP_ART_SEQUENCE_STATUS_BAD_OPCODE_SHIFT                  21

/* ART :: SEQUENCE_STATUS :: CODE_STORE_WRAP [20:20] */
#define BCHP_ART_SEQUENCE_STATUS_CODE_STORE_WRAP_MASK              0x00100000
#define BCHP_ART_SEQUENCE_STATUS_CODE_STORE_WRAP_SHIFT             20

/* ART :: SEQUENCE_STATUS :: EXECUTED_HALT [19:19] */
#define BCHP_ART_SEQUENCE_STATUS_EXECUTED_HALT_MASK                0x00080000
#define BCHP_ART_SEQUENCE_STATUS_EXECUTED_HALT_SHIFT               19

/* ART :: SEQUENCE_STATUS :: GOT_STOP_TRIGGER [18:18] */
#define BCHP_ART_SEQUENCE_STATUS_GOT_STOP_TRIGGER_MASK             0x00040000
#define BCHP_ART_SEQUENCE_STATUS_GOT_STOP_TRIGGER_SHIFT            18

/* ART :: SEQUENCE_STATUS :: GOT_START_TRIGGER [17:17] */
#define BCHP_ART_SEQUENCE_STATUS_GOT_START_TRIGGER_MASK            0x00020000
#define BCHP_ART_SEQUENCE_STATUS_GOT_START_TRIGGER_SHIFT           17

/* ART :: SEQUENCE_STATUS :: GOT_WAKEUP [16:16] */
#define BCHP_ART_SEQUENCE_STATUS_GOT_WAKEUP_MASK                   0x00010000
#define BCHP_ART_SEQUENCE_STATUS_GOT_WAKEUP_SHIFT                  16

/* ART :: SEQUENCE_STATUS :: reserved1 [15:08] */
#define BCHP_ART_SEQUENCE_STATUS_reserved1_MASK                    0x0000ff00
#define BCHP_ART_SEQUENCE_STATUS_reserved1_SHIFT                   8

/* ART :: SEQUENCE_STATUS :: CURRENT_POINTER [07:00] */
#define BCHP_ART_SEQUENCE_STATUS_CURRENT_POINTER_MASK              0x000000ff
#define BCHP_ART_SEQUENCE_STATUS_CURRENT_POINTER_SHIFT             0

/***************************************************************************
 *CODESTORE_POINTER - Address for Access to Code Store Memory
 ***************************************************************************/
/* ART :: CODESTORE_POINTER :: reserved0 [31:08] */
#define BCHP_ART_CODESTORE_POINTER_reserved0_MASK                  0xffffff00
#define BCHP_ART_CODESTORE_POINTER_reserved0_SHIFT                 8

/* ART :: CODESTORE_POINTER :: POINTER [07:00] */
#define BCHP_ART_CODESTORE_POINTER_POINTER_MASK                    0x000000ff
#define BCHP_ART_CODESTORE_POINTER_POINTER_SHIFT                   0

/***************************************************************************
 *CODESTORE_DATA - Data Word for Access to Code Store Memory
 ***************************************************************************/
/* ART :: CODESTORE_DATA :: DATA_WORD [31:00] */
#define BCHP_ART_CODESTORE_DATA_DATA_WORD_MASK                     0xffffffff
#define BCHP_ART_CODESTORE_DATA_DATA_WORD_SHIFT                    0

/***************************************************************************
 *CODESTORE_TM - Code Store Memory Test Mode Control
 ***************************************************************************/
/* ART :: CODESTORE_TM :: reserved0 [31:04] */
#define BCHP_ART_CODESTORE_TM_reserved0_MASK                       0xfffffff0
#define BCHP_ART_CODESTORE_TM_reserved0_SHIFT                      4

/* ART :: CODESTORE_TM :: TM [03:00] */
#define BCHP_ART_CODESTORE_TM_TM_MASK                              0x0000000f
#define BCHP_ART_CODESTORE_TM_TM_SHIFT                             0

/***************************************************************************
 *DEBUG - ART Debug Output
 ***************************************************************************/
/* ART :: DEBUG :: reserved0 [31:01] */
#define BCHP_ART_DEBUG_reserved0_MASK                              0xfffffffe
#define BCHP_ART_DEBUG_reserved0_SHIFT                             1

/* ART :: DEBUG :: ART_OUT [00:00] */
#define BCHP_ART_DEBUG_ART_OUT_MASK                                0x00000001
#define BCHP_ART_DEBUG_ART_OUT_SHIFT                               0

#endif /* #ifndef BCHP_ART_H__ */

/* End of File */
