/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_sharf_mem_dma1.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 5/14/09 1:50a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed May 13 17:34:49 2009
 *                 MD5 Checksum         397c7e3e68fca5836958d6d3dcfe31f9
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7630/rdb/b0/bchp_sharf_mem_dma1.h $
 * 
 * Hydra_Software_Devel/1   5/14/09 1:50a tdo
 * PR55087: Initial check in
 *
 ***************************************************************************/

#ifndef BCHP_SHARF_MEM_DMA1_H__
#define BCHP_SHARF_MEM_DMA1_H__

/***************************************************************************
 *SHARF_MEM_DMA1 - SHARF_MEM_DMA Channel 1 Registers
 ***************************************************************************/
#define BCHP_SHARF_MEM_DMA1_FIRST_DESC           0x01404200 /* SHARF_MEM_DMA First Descriptor Address Register */
#define BCHP_SHARF_MEM_DMA1_CTRL                 0x01404204 /* SHARF_MEM_DMA Control Register */
#define BCHP_SHARF_MEM_DMA1_WAKE_CTRL            0x01404208 /* SHARF_MEM_DMA Wake Control Register */
#define BCHP_SHARF_MEM_DMA1_STATUS               0x01404210 /* SHARF_MEM_DMA Status Register */
#define BCHP_SHARF_MEM_DMA1_CUR_DESC             0x01404214 /* SHARF_MEM_DMA  Current Descriptor Address Register */
#define BCHP_SHARF_MEM_DMA1_CUR_BYTE             0x01404218 /* SHARF_MEM_DMA  Current Byte Count Register */
#define BCHP_SHARF_MEM_DMA1_SCRATCH              0x0140421c /* SHARF_MEM_DMA Scratch Register */

#endif /* #ifndef BCHP_SHARF_MEM_DMA1_H__ */

/* End of File */
