/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_vide_host_reg.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 5/14/09 2:06a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed May 13 17:31:20 2009
 *                 MD5 Checksum         397c7e3e68fca5836958d6d3dcfe31f9
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7630/rdb/b0/bchp_vide_host_reg.h $
 * 
 * Hydra_Software_Devel/1   5/14/09 2:06a tdo
 * PR55087: Initial check in
 *
 ***************************************************************************/

#ifndef BCHP_VIDE_HOST_REG_H__
#define BCHP_VIDE_HOST_REG_H__

/***************************************************************************
 *VIDE_HOST_REG
 ***************************************************************************/
#define BCHP_VIDE_HOST_REG_REG_0                 0x00290000 /* "Host word 0" */
#define BCHP_VIDE_HOST_REG_REG_1                 0x00290004 /* "Host word 1" */
#define BCHP_VIDE_HOST_REG_REG_2                 0x00290014 /* "Host Control Word" */
#define BCHP_VIDE_HOST_REG_ALIAS_HOST            0x00290100 /* "Alias: Host data" */
#define BCHP_VIDE_HOST_REG_ALIAS_FEATURES        0x00290104 /* "Alias: Features" */
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_CNT      0x00290108 /* "Alias: Sector cnt" */
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_NUM      0x0029010c /* "Alias: Sector num" */
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_LOW    0x00290110 /* "Alias: Cylinder low" */
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_HIGH   0x00290114 /* "Alias: Cylinder high" */
#define BCHP_VIDE_HOST_REG_ALIAS_DEVICE_HEAD     0x00290118 /* "Alias: Device head" */
#define BCHP_VIDE_HOST_REG_ALIAS_COMMAND_STATUS  0x0029011c /* "Alias: Command status" */
#define BCHP_VIDE_HOST_REG_ALIAS_ALT_STATUS      0x00290158 /* "Alias: Alt status" */

/***************************************************************************
 *REG_0 - "Host word 0"
 ***************************************************************************/
/* VIDE_HOST_REG :: REG_0 :: SectorNumber [31:24] */
#define BCHP_VIDE_HOST_REG_REG_0_SectorNumber_MASK                 0xff000000
#define BCHP_VIDE_HOST_REG_REG_0_SectorNumber_SHIFT                24

/* VIDE_HOST_REG :: REG_0 :: SectorCnt [23:16] */
#define BCHP_VIDE_HOST_REG_REG_0_SectorCnt_MASK                    0x00ff0000
#define BCHP_VIDE_HOST_REG_REG_0_SectorCnt_SHIFT                   16

/* VIDE_HOST_REG :: REG_0 :: Features [15:08] */
#define BCHP_VIDE_HOST_REG_REG_0_Features_MASK                     0x0000ff00
#define BCHP_VIDE_HOST_REG_REG_0_Features_SHIFT                    8

/* VIDE_HOST_REG :: REG_0 :: Data [07:00] */
#define BCHP_VIDE_HOST_REG_REG_0_Data_MASK                         0x000000ff
#define BCHP_VIDE_HOST_REG_REG_0_Data_SHIFT                        0

/***************************************************************************
 *REG_1 - "Host word 1"
 ***************************************************************************/
/* VIDE_HOST_REG :: REG_1 :: CommandStatus [31:24] */
#define BCHP_VIDE_HOST_REG_REG_1_CommandStatus_MASK                0xff000000
#define BCHP_VIDE_HOST_REG_REG_1_CommandStatus_SHIFT               24

/* VIDE_HOST_REG :: REG_1 :: DeviceHead [23:16] */
#define BCHP_VIDE_HOST_REG_REG_1_DeviceHead_MASK                   0x00ff0000
#define BCHP_VIDE_HOST_REG_REG_1_DeviceHead_SHIFT                  16

/* VIDE_HOST_REG :: REG_1 :: CylinderHigh [15:08] */
#define BCHP_VIDE_HOST_REG_REG_1_CylinderHigh_MASK                 0x0000ff00
#define BCHP_VIDE_HOST_REG_REG_1_CylinderHigh_SHIFT                8

/* VIDE_HOST_REG :: REG_1 :: CylinderLow [07:00] */
#define BCHP_VIDE_HOST_REG_REG_1_CylinderLow_MASK                  0x000000ff
#define BCHP_VIDE_HOST_REG_REG_1_CylinderLow_SHIFT                 0

/***************************************************************************
 *REG_2 - "Host Control Word"
 ***************************************************************************/
/* VIDE_HOST_REG :: REG_2 :: reserved0 [31:24] */
#define BCHP_VIDE_HOST_REG_REG_2_reserved0_MASK                    0xff000000
#define BCHP_VIDE_HOST_REG_REG_2_reserved0_SHIFT                   24

/* VIDE_HOST_REG :: REG_2 :: DeviceCtlAltStatus [23:16] */
#define BCHP_VIDE_HOST_REG_REG_2_DeviceCtlAltStatus_MASK           0x00ff0000
#define BCHP_VIDE_HOST_REG_REG_2_DeviceCtlAltStatus_SHIFT          16

/* VIDE_HOST_REG :: REG_2 :: reserved1 [15:00] */
#define BCHP_VIDE_HOST_REG_REG_2_reserved1_MASK                    0x0000ffff
#define BCHP_VIDE_HOST_REG_REG_2_reserved1_SHIFT                   0

/***************************************************************************
 *ALIAS_HOST - "Alias: Host data"
 ***************************************************************************/
/* VIDE_HOST_REG :: ALIAS_HOST :: reserved0 [31:16] */
#define BCHP_VIDE_HOST_REG_ALIAS_HOST_reserved0_MASK               0xffff0000
#define BCHP_VIDE_HOST_REG_ALIAS_HOST_reserved0_SHIFT              16

/* VIDE_HOST_REG :: ALIAS_HOST :: Data [15:00] */
#define BCHP_VIDE_HOST_REG_ALIAS_HOST_Data_MASK                    0x0000ffff
#define BCHP_VIDE_HOST_REG_ALIAS_HOST_Data_SHIFT                   0

/***************************************************************************
 *ALIAS_FEATURES - "Alias: Features"
 ***************************************************************************/
/* VIDE_HOST_REG :: ALIAS_FEATURES :: reserved0 [31:08] */
#define BCHP_VIDE_HOST_REG_ALIAS_FEATURES_reserved0_MASK           0xffffff00
#define BCHP_VIDE_HOST_REG_ALIAS_FEATURES_reserved0_SHIFT          8

/* VIDE_HOST_REG :: ALIAS_FEATURES :: Features [07:00] */
#define BCHP_VIDE_HOST_REG_ALIAS_FEATURES_Features_MASK            0x000000ff
#define BCHP_VIDE_HOST_REG_ALIAS_FEATURES_Features_SHIFT           0

/***************************************************************************
 *ALIAS_SECTOR_CNT - "Alias: Sector cnt"
 ***************************************************************************/
/* VIDE_HOST_REG :: ALIAS_SECTOR_CNT :: reserved0 [31:08] */
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_CNT_reserved0_MASK         0xffffff00
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_CNT_reserved0_SHIFT        8

/* VIDE_HOST_REG :: ALIAS_SECTOR_CNT :: Features [07:00] */
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_CNT_Features_MASK          0x000000ff
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_CNT_Features_SHIFT         0

/***************************************************************************
 *ALIAS_SECTOR_NUM - "Alias: Sector num"
 ***************************************************************************/
/* VIDE_HOST_REG :: ALIAS_SECTOR_NUM :: reserved0 [31:08] */
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_NUM_reserved0_MASK         0xffffff00
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_NUM_reserved0_SHIFT        8

/* VIDE_HOST_REG :: ALIAS_SECTOR_NUM :: SectorNumber [07:00] */
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_NUM_SectorNumber_MASK      0x000000ff
#define BCHP_VIDE_HOST_REG_ALIAS_SECTOR_NUM_SectorNumber_SHIFT     0

/***************************************************************************
 *ALIAS_CYLINDER_LOW - "Alias: Cylinder low"
 ***************************************************************************/
/* VIDE_HOST_REG :: ALIAS_CYLINDER_LOW :: reserved0 [31:08] */
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_LOW_reserved0_MASK       0xffffff00
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_LOW_reserved0_SHIFT      8

/* VIDE_HOST_REG :: ALIAS_CYLINDER_LOW :: CylinderLow [07:00] */
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_LOW_CylinderLow_MASK     0x000000ff
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_LOW_CylinderLow_SHIFT    0

/***************************************************************************
 *ALIAS_CYLINDER_HIGH - "Alias: Cylinder high"
 ***************************************************************************/
/* VIDE_HOST_REG :: ALIAS_CYLINDER_HIGH :: reserved0 [31:08] */
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_HIGH_reserved0_MASK      0xffffff00
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_HIGH_reserved0_SHIFT     8

/* VIDE_HOST_REG :: ALIAS_CYLINDER_HIGH :: CylinderHigh [07:00] */
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_HIGH_CylinderHigh_MASK   0x000000ff
#define BCHP_VIDE_HOST_REG_ALIAS_CYLINDER_HIGH_CylinderHigh_SHIFT  0

/***************************************************************************
 *ALIAS_DEVICE_HEAD - "Alias: Device head"
 ***************************************************************************/
/* VIDE_HOST_REG :: ALIAS_DEVICE_HEAD :: reserved0 [31:08] */
#define BCHP_VIDE_HOST_REG_ALIAS_DEVICE_HEAD_reserved0_MASK        0xffffff00
#define BCHP_VIDE_HOST_REG_ALIAS_DEVICE_HEAD_reserved0_SHIFT       8

/* VIDE_HOST_REG :: ALIAS_DEVICE_HEAD :: DeviceHead [07:00] */
#define BCHP_VIDE_HOST_REG_ALIAS_DEVICE_HEAD_DeviceHead_MASK       0x000000ff
#define BCHP_VIDE_HOST_REG_ALIAS_DEVICE_HEAD_DeviceHead_SHIFT      0

/***************************************************************************
 *ALIAS_COMMAND_STATUS - "Alias: Command status"
 ***************************************************************************/
/* VIDE_HOST_REG :: ALIAS_COMMAND_STATUS :: reserved0 [31:08] */
#define BCHP_VIDE_HOST_REG_ALIAS_COMMAND_STATUS_reserved0_MASK     0xffffff00
#define BCHP_VIDE_HOST_REG_ALIAS_COMMAND_STATUS_reserved0_SHIFT    8

/* VIDE_HOST_REG :: ALIAS_COMMAND_STATUS :: CmdStatus [07:00] */
#define BCHP_VIDE_HOST_REG_ALIAS_COMMAND_STATUS_CmdStatus_MASK     0x000000ff
#define BCHP_VIDE_HOST_REG_ALIAS_COMMAND_STATUS_CmdStatus_SHIFT    0

/***************************************************************************
 *ALIAS_ALT_STATUS - "Alias: Alt status"
 ***************************************************************************/
/* VIDE_HOST_REG :: ALIAS_ALT_STATUS :: reserved0 [31:08] */
#define BCHP_VIDE_HOST_REG_ALIAS_ALT_STATUS_reserved0_MASK         0xffffff00
#define BCHP_VIDE_HOST_REG_ALIAS_ALT_STATUS_reserved0_SHIFT        8

/* VIDE_HOST_REG :: ALIAS_ALT_STATUS :: AltStatus [07:00] */
#define BCHP_VIDE_HOST_REG_ALIAS_ALT_STATUS_AltStatus_MASK         0x000000ff
#define BCHP_VIDE_HOST_REG_ALIAS_ALT_STATUS_AltStatus_SHIFT        0

#endif /* #ifndef BCHP_VIDE_HOST_REG_H__ */

/* End of File */
