/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed with the hope that it will be useful, but without
 * any warranty; without even the implied warranty of merchantability or
 * fitness for a particular purpose.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * $brcm_Workfile: bchp_misc.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 5/14/09 1:28a $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed May 13 17:36:57 2009
 *                 MD5 Checksum         397c7e3e68fca5836958d6d3dcfe31f9
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7630/rdb/b0/bchp_misc.h $
 * 
 * Hydra_Software_Devel/1   5/14/09 1:28a tdo
 * PR55087: Initial check in
 *
 ***************************************************************************/

#ifndef BCHP_MISC_H__
#define BCHP_MISC_H__

/***************************************************************************
 *MISC - VEC Registers
 ***************************************************************************/
#define BCHP_MISC_MISC_REVISION_ID               0x00180900 /* Revision ID Register */
#define BCHP_MISC_DELAY_REG                      0x00180904 /* DELAY Register for DACs */
#define BCHP_MISC_OUT_MUX                        0x00180908 /* Output muxing */
#define BCHP_MISC_DAC0_1_CONST                   0x0018090c /* DAC0 & DAC1 Const Vals */
#define BCHP_MISC_DAC2_3_CONST                   0x00180910 /* DAC2 & DAC3 Const Vals */
#define BCHP_MISC_DAC4_5_CONST                   0x00180914 /* DAC4 & DAC5 Const Vals */
#define BCHP_MISC_OUT_CTRL                       0x00180918 /* Output Control */
#define BCHP_MISC_SEC_CO_CH0_SA_STATUS           0x0018091c /* SEC Component-Only Channel 0 SA Status Register */
#define BCHP_MISC_SEC_CO_CH1_SA_STATUS           0x00180920 /* SEC Component-Only Channel 1 SA Status Register */
#define BCHP_MISC_SEC_CO_CH2_SA_STATUS           0x00180924 /* SEC Component-Only Channel 2 SA Status Register */
#define BCHP_MISC_SEC_CO_SA_CONFIG               0x00180928 /* SEC Component-Only SA Config Register */
#define BCHP_MISC_SYNC_DELAY_REG                 0x00180934 /* DELAY Register for Digital Sync */
#define BCHP_MISC_DVI_SA_CONFIG                  0x00180938 /* DVI SA Configuration Register */
#define BCHP_MISC_DVI_SA_STATUS                  0x0018093c /* DVI SA Status Register */
#define BCHP_MISC_PRIM_MASTER_SEL                0x00180940 /* Master Select for Primary VEC path */
#define BCHP_MISC_SEC_MASTER_SEL                 0x00180944 /* Master Select for Secondary VEC path */
#define BCHP_MISC_DVI_MASTER_SEL                 0x0018094c /* Master Select for DVI VEC path */
#define BCHP_MISC_DAC_BG_CTRL_REG                0x00180954 /* HEXDAC Bandgap Control Register */
#define BCHP_MISC_DAC1_CTRL_REG                  0x00180958 /* HEXDAC1 Control Register */
#define BCHP_MISC_DAC2_CTRL_REG                  0x0018095c /* HEXDAC2 Control Register */
#define BCHP_MISC_DAC3_CTRL_REG                  0x00180960 /* HEXDAC3 Control Register */
#define BCHP_MISC_DAC4_CTRL_REG                  0x00180964 /* HEXDAC4 Control Register */
#define BCHP_MISC_DAC5_CTRL_REG                  0x00180968 /* HEXDAC5 Control Register */
#define BCHP_MISC_DAC6_CTRL_REG                  0x0018096c /* HEXDAC6 Control Register */
#define BCHP_MISC_DVI_DITHERING                  0x00180974 /* DVI Dithering Register */
#define BCHP_MISC_PRIM_CH0_SA_STATUS             0x00180978 /* PRIM Channel 0 SA Status Register */
#define BCHP_MISC_PRIM_CH1_SA_STATUS             0x0018097c /* PRIM Channel 1 SA Status Register */
#define BCHP_MISC_PRIM_CH2_SA_STATUS             0x00180980 /* PRIM Channel 2 SA Status Register */
#define BCHP_MISC_PRIM_SA_CONFIG                 0x00180984 /* PRIM SA Config Register */

/***************************************************************************
 *MISC_REVISION_ID - Revision ID Register
 ***************************************************************************/
/* MISC :: MISC_REVISION_ID :: reserved0 [31:16] */
#define BCHP_MISC_MISC_REVISION_ID_reserved0_MASK                  0xffff0000
#define BCHP_MISC_MISC_REVISION_ID_reserved0_SHIFT                 16

/* MISC :: MISC_REVISION_ID :: REVISION_ID [15:00] */
#define BCHP_MISC_MISC_REVISION_ID_REVISION_ID_MASK                0x0000ffff
#define BCHP_MISC_MISC_REVISION_ID_REVISION_ID_SHIFT               0

/***************************************************************************
 *DELAY_REG - DELAY Register for DACs
 ***************************************************************************/
/* MISC :: DELAY_REG :: reserved0 [31:12] */
#define BCHP_MISC_DELAY_REG_reserved0_MASK                         0xfffff000
#define BCHP_MISC_DELAY_REG_reserved0_SHIFT                        12

/* MISC :: DELAY_REG :: DAC_5 [11:10] */
#define BCHP_MISC_DELAY_REG_DAC_5_MASK                             0x00000c00
#define BCHP_MISC_DELAY_REG_DAC_5_SHIFT                            10

/* MISC :: DELAY_REG :: DAC_4 [09:08] */
#define BCHP_MISC_DELAY_REG_DAC_4_MASK                             0x00000300
#define BCHP_MISC_DELAY_REG_DAC_4_SHIFT                            8

/* MISC :: DELAY_REG :: DAC_3 [07:06] */
#define BCHP_MISC_DELAY_REG_DAC_3_MASK                             0x000000c0
#define BCHP_MISC_DELAY_REG_DAC_3_SHIFT                            6

/* MISC :: DELAY_REG :: DAC_2 [05:04] */
#define BCHP_MISC_DELAY_REG_DAC_2_MASK                             0x00000030
#define BCHP_MISC_DELAY_REG_DAC_2_SHIFT                            4

/* MISC :: DELAY_REG :: DAC_1 [03:02] */
#define BCHP_MISC_DELAY_REG_DAC_1_MASK                             0x0000000c
#define BCHP_MISC_DELAY_REG_DAC_1_SHIFT                            2

/* MISC :: DELAY_REG :: DAC_0 [01:00] */
#define BCHP_MISC_DELAY_REG_DAC_0_MASK                             0x00000003
#define BCHP_MISC_DELAY_REG_DAC_0_SHIFT                            0

/***************************************************************************
 *OUT_MUX - Output muxing
 ***************************************************************************/
/* MISC :: OUT_MUX :: reserved0 [31:24] */
#define BCHP_MISC_OUT_MUX_reserved0_MASK                           0xff000000
#define BCHP_MISC_OUT_MUX_reserved0_SHIFT                          24

/* MISC :: OUT_MUX :: DAC5_SEL [23:20] */
#define BCHP_MISC_OUT_MUX_DAC5_SEL_MASK                            0x00f00000
#define BCHP_MISC_OUT_MUX_DAC5_SEL_SHIFT                           20
#define BCHP_MISC_OUT_MUX_DAC5_SEL_CONST                           0
#define BCHP_MISC_OUT_MUX_DAC5_SEL_PRIM_CH0                        1
#define BCHP_MISC_OUT_MUX_DAC5_SEL_PRIM_CH1                        2
#define BCHP_MISC_OUT_MUX_DAC5_SEL_PRIM_CH2                        3
#define BCHP_MISC_OUT_MUX_DAC5_SEL_SEC_CH0                         4
#define BCHP_MISC_OUT_MUX_DAC5_SEL_SEC_CH1                         5
#define BCHP_MISC_OUT_MUX_DAC5_SEL_SEC_CH2                         6
#define BCHP_MISC_OUT_MUX_DAC5_SEL_SEC_CO_CH0                      7
#define BCHP_MISC_OUT_MUX_DAC5_SEL_SEC_CO_CH1                      8
#define BCHP_MISC_OUT_MUX_DAC5_SEL_SEC_CO_CH2                      9

/* MISC :: OUT_MUX :: DAC4_SEL [19:16] */
#define BCHP_MISC_OUT_MUX_DAC4_SEL_MASK                            0x000f0000
#define BCHP_MISC_OUT_MUX_DAC4_SEL_SHIFT                           16
#define BCHP_MISC_OUT_MUX_DAC4_SEL_CONST                           0
#define BCHP_MISC_OUT_MUX_DAC4_SEL_PRIM_CH0                        1
#define BCHP_MISC_OUT_MUX_DAC4_SEL_PRIM_CH1                        2
#define BCHP_MISC_OUT_MUX_DAC4_SEL_PRIM_CH2                        3
#define BCHP_MISC_OUT_MUX_DAC4_SEL_SEC_CH0                         4
#define BCHP_MISC_OUT_MUX_DAC4_SEL_SEC_CH1                         5
#define BCHP_MISC_OUT_MUX_DAC4_SEL_SEC_CH2                         6
#define BCHP_MISC_OUT_MUX_DAC4_SEL_SEC_CO_CH0                      7
#define BCHP_MISC_OUT_MUX_DAC4_SEL_SEC_CO_CH1                      8
#define BCHP_MISC_OUT_MUX_DAC4_SEL_SEC_CO_CH2                      9

/* MISC :: OUT_MUX :: DAC3_SEL [15:12] */
#define BCHP_MISC_OUT_MUX_DAC3_SEL_MASK                            0x0000f000
#define BCHP_MISC_OUT_MUX_DAC3_SEL_SHIFT                           12
#define BCHP_MISC_OUT_MUX_DAC3_SEL_CONST                           0
#define BCHP_MISC_OUT_MUX_DAC3_SEL_PRIM_CH0                        1
#define BCHP_MISC_OUT_MUX_DAC3_SEL_PRIM_CH1                        2
#define BCHP_MISC_OUT_MUX_DAC3_SEL_PRIM_CH2                        3
#define BCHP_MISC_OUT_MUX_DAC3_SEL_SEC_CH0                         4
#define BCHP_MISC_OUT_MUX_DAC3_SEL_SEC_CH1                         5
#define BCHP_MISC_OUT_MUX_DAC3_SEL_SEC_CH2                         6
#define BCHP_MISC_OUT_MUX_DAC3_SEL_SEC_CO_CH0                      7
#define BCHP_MISC_OUT_MUX_DAC3_SEL_SEC_CO_CH1                      8
#define BCHP_MISC_OUT_MUX_DAC3_SEL_SEC_CO_CH2                      9

/* MISC :: OUT_MUX :: DAC2_SEL [11:08] */
#define BCHP_MISC_OUT_MUX_DAC2_SEL_MASK                            0x00000f00
#define BCHP_MISC_OUT_MUX_DAC2_SEL_SHIFT                           8
#define BCHP_MISC_OUT_MUX_DAC2_SEL_CONST                           0
#define BCHP_MISC_OUT_MUX_DAC2_SEL_PRIM_CH0                        1
#define BCHP_MISC_OUT_MUX_DAC2_SEL_PRIM_CH1                        2
#define BCHP_MISC_OUT_MUX_DAC2_SEL_PRIM_CH2                        3
#define BCHP_MISC_OUT_MUX_DAC2_SEL_SEC_CH0                         4
#define BCHP_MISC_OUT_MUX_DAC2_SEL_SEC_CH1                         5
#define BCHP_MISC_OUT_MUX_DAC2_SEL_SEC_CH2                         6
#define BCHP_MISC_OUT_MUX_DAC2_SEL_SEC_CO_CH0                      7
#define BCHP_MISC_OUT_MUX_DAC2_SEL_SEC_CO_CH1                      8
#define BCHP_MISC_OUT_MUX_DAC2_SEL_SEC_CO_CH2                      9

/* MISC :: OUT_MUX :: DAC1_SEL [07:04] */
#define BCHP_MISC_OUT_MUX_DAC1_SEL_MASK                            0x000000f0
#define BCHP_MISC_OUT_MUX_DAC1_SEL_SHIFT                           4
#define BCHP_MISC_OUT_MUX_DAC1_SEL_CONST                           0
#define BCHP_MISC_OUT_MUX_DAC1_SEL_PRIM_CH0                        1
#define BCHP_MISC_OUT_MUX_DAC1_SEL_PRIM_CH1                        2
#define BCHP_MISC_OUT_MUX_DAC1_SEL_PRIM_CH2                        3
#define BCHP_MISC_OUT_MUX_DAC1_SEL_SEC_CH0                         4
#define BCHP_MISC_OUT_MUX_DAC1_SEL_SEC_CH1                         5
#define BCHP_MISC_OUT_MUX_DAC1_SEL_SEC_CH2                         6
#define BCHP_MISC_OUT_MUX_DAC1_SEL_SEC_CO_CH0                      7
#define BCHP_MISC_OUT_MUX_DAC1_SEL_SEC_CO_CH1                      8
#define BCHP_MISC_OUT_MUX_DAC1_SEL_SEC_CO_CH2                      9

/* MISC :: OUT_MUX :: DAC0_SEL [03:00] */
#define BCHP_MISC_OUT_MUX_DAC0_SEL_MASK                            0x0000000f
#define BCHP_MISC_OUT_MUX_DAC0_SEL_SHIFT                           0
#define BCHP_MISC_OUT_MUX_DAC0_SEL_CONST                           0
#define BCHP_MISC_OUT_MUX_DAC0_SEL_PRIM_CH0                        1
#define BCHP_MISC_OUT_MUX_DAC0_SEL_PRIM_CH1                        2
#define BCHP_MISC_OUT_MUX_DAC0_SEL_PRIM_CH2                        3
#define BCHP_MISC_OUT_MUX_DAC0_SEL_SEC_CH0                         4
#define BCHP_MISC_OUT_MUX_DAC0_SEL_SEC_CH1                         5
#define BCHP_MISC_OUT_MUX_DAC0_SEL_SEC_CH2                         6
#define BCHP_MISC_OUT_MUX_DAC0_SEL_SEC_CO_CH0                      7
#define BCHP_MISC_OUT_MUX_DAC0_SEL_SEC_CO_CH1                      8
#define BCHP_MISC_OUT_MUX_DAC0_SEL_SEC_CO_CH2                      9

/***************************************************************************
 *DAC0_1_CONST - DAC0 & DAC1 Const Vals
 ***************************************************************************/
/* MISC :: DAC0_1_CONST :: reserved0 [31:24] */
#define BCHP_MISC_DAC0_1_CONST_reserved0_MASK                      0xff000000
#define BCHP_MISC_DAC0_1_CONST_reserved0_SHIFT                     24

/* MISC :: DAC0_1_CONST :: DAC_1_CONST [23:12] */
#define BCHP_MISC_DAC0_1_CONST_DAC_1_CONST_MASK                    0x00fff000
#define BCHP_MISC_DAC0_1_CONST_DAC_1_CONST_SHIFT                   12

/* MISC :: DAC0_1_CONST :: DAC_0_CONST [11:00] */
#define BCHP_MISC_DAC0_1_CONST_DAC_0_CONST_MASK                    0x00000fff
#define BCHP_MISC_DAC0_1_CONST_DAC_0_CONST_SHIFT                   0

/***************************************************************************
 *DAC2_3_CONST - DAC2 & DAC3 Const Vals
 ***************************************************************************/
/* MISC :: DAC2_3_CONST :: reserved0 [31:24] */
#define BCHP_MISC_DAC2_3_CONST_reserved0_MASK                      0xff000000
#define BCHP_MISC_DAC2_3_CONST_reserved0_SHIFT                     24

/* MISC :: DAC2_3_CONST :: DAC_3_CONST [23:12] */
#define BCHP_MISC_DAC2_3_CONST_DAC_3_CONST_MASK                    0x00fff000
#define BCHP_MISC_DAC2_3_CONST_DAC_3_CONST_SHIFT                   12

/* MISC :: DAC2_3_CONST :: DAC_2_CONST [11:00] */
#define BCHP_MISC_DAC2_3_CONST_DAC_2_CONST_MASK                    0x00000fff
#define BCHP_MISC_DAC2_3_CONST_DAC_2_CONST_SHIFT                   0

/***************************************************************************
 *DAC4_5_CONST - DAC4 & DAC5 Const Vals
 ***************************************************************************/
/* MISC :: DAC4_5_CONST :: reserved0 [31:24] */
#define BCHP_MISC_DAC4_5_CONST_reserved0_MASK                      0xff000000
#define BCHP_MISC_DAC4_5_CONST_reserved0_SHIFT                     24

/* MISC :: DAC4_5_CONST :: DAC_5_CONST [23:12] */
#define BCHP_MISC_DAC4_5_CONST_DAC_5_CONST_MASK                    0x00fff000
#define BCHP_MISC_DAC4_5_CONST_DAC_5_CONST_SHIFT                   12

/* MISC :: DAC4_5_CONST :: DAC_4_CONST [11:00] */
#define BCHP_MISC_DAC4_5_CONST_DAC_4_CONST_MASK                    0x00000fff
#define BCHP_MISC_DAC4_5_CONST_DAC_4_CONST_SHIFT                   0

/***************************************************************************
 *OUT_CTRL - Output Control
 ***************************************************************************/
/* MISC :: OUT_CTRL :: reserved0 [31:06] */
#define BCHP_MISC_OUT_CTRL_reserved0_MASK                          0xffffffc0
#define BCHP_MISC_OUT_CTRL_reserved0_SHIFT                         6

/* MISC :: OUT_CTRL :: DAC5_SINC [05:05] */
#define BCHP_MISC_OUT_CTRL_DAC5_SINC_MASK                          0x00000020
#define BCHP_MISC_OUT_CTRL_DAC5_SINC_SHIFT                         5
#define BCHP_MISC_OUT_CTRL_DAC5_SINC_ON                            1
#define BCHP_MISC_OUT_CTRL_DAC5_SINC_OFF                           0

/* MISC :: OUT_CTRL :: DAC4_SINC [04:04] */
#define BCHP_MISC_OUT_CTRL_DAC4_SINC_MASK                          0x00000010
#define BCHP_MISC_OUT_CTRL_DAC4_SINC_SHIFT                         4
#define BCHP_MISC_OUT_CTRL_DAC4_SINC_ON                            1
#define BCHP_MISC_OUT_CTRL_DAC4_SINC_OFF                           0

/* MISC :: OUT_CTRL :: DAC3_SINC [03:03] */
#define BCHP_MISC_OUT_CTRL_DAC3_SINC_MASK                          0x00000008
#define BCHP_MISC_OUT_CTRL_DAC3_SINC_SHIFT                         3
#define BCHP_MISC_OUT_CTRL_DAC3_SINC_ON                            1
#define BCHP_MISC_OUT_CTRL_DAC3_SINC_OFF                           0

/* MISC :: OUT_CTRL :: DAC2_SINC [02:02] */
#define BCHP_MISC_OUT_CTRL_DAC2_SINC_MASK                          0x00000004
#define BCHP_MISC_OUT_CTRL_DAC2_SINC_SHIFT                         2
#define BCHP_MISC_OUT_CTRL_DAC2_SINC_ON                            1
#define BCHP_MISC_OUT_CTRL_DAC2_SINC_OFF                           0

/* MISC :: OUT_CTRL :: DAC1_SINC [01:01] */
#define BCHP_MISC_OUT_CTRL_DAC1_SINC_MASK                          0x00000002
#define BCHP_MISC_OUT_CTRL_DAC1_SINC_SHIFT                         1
#define BCHP_MISC_OUT_CTRL_DAC1_SINC_ON                            1
#define BCHP_MISC_OUT_CTRL_DAC1_SINC_OFF                           0

/* MISC :: OUT_CTRL :: DAC0_SINC [00:00] */
#define BCHP_MISC_OUT_CTRL_DAC0_SINC_MASK                          0x00000001
#define BCHP_MISC_OUT_CTRL_DAC0_SINC_SHIFT                         0
#define BCHP_MISC_OUT_CTRL_DAC0_SINC_ON                            1
#define BCHP_MISC_OUT_CTRL_DAC0_SINC_OFF                           0

/***************************************************************************
 *SEC_CO_CH0_SA_STATUS - SEC Component-Only Channel 0 SA Status Register
 ***************************************************************************/
/* MISC :: SEC_CO_CH0_SA_STATUS :: STATUS [31:00] */
#define BCHP_MISC_SEC_CO_CH0_SA_STATUS_STATUS_MASK                 0xffffffff
#define BCHP_MISC_SEC_CO_CH0_SA_STATUS_STATUS_SHIFT                0

/***************************************************************************
 *SEC_CO_CH1_SA_STATUS - SEC Component-Only Channel 1 SA Status Register
 ***************************************************************************/
/* MISC :: SEC_CO_CH1_SA_STATUS :: STATUS [31:00] */
#define BCHP_MISC_SEC_CO_CH1_SA_STATUS_STATUS_MASK                 0xffffffff
#define BCHP_MISC_SEC_CO_CH1_SA_STATUS_STATUS_SHIFT                0

/***************************************************************************
 *SEC_CO_CH2_SA_STATUS - SEC Component-Only Channel 2 SA Status Register
 ***************************************************************************/
/* MISC :: SEC_CO_CH2_SA_STATUS :: STATUS [31:00] */
#define BCHP_MISC_SEC_CO_CH2_SA_STATUS_STATUS_MASK                 0xffffffff
#define BCHP_MISC_SEC_CO_CH2_SA_STATUS_STATUS_SHIFT                0

/***************************************************************************
 *SEC_CO_SA_CONFIG - SEC Component-Only SA Config Register
 ***************************************************************************/
/* MISC :: SEC_CO_SA_CONFIG :: reserved0 [31:11] */
#define BCHP_MISC_SEC_CO_SA_CONFIG_reserved0_MASK                  0xfffff800
#define BCHP_MISC_SEC_CO_SA_CONFIG_reserved0_SHIFT                 11

/* MISC :: SEC_CO_SA_CONFIG :: EDGE_SELECT [10:09] */
#define BCHP_MISC_SEC_CO_SA_CONFIG_EDGE_SELECT_MASK                0x00000600
#define BCHP_MISC_SEC_CO_SA_CONFIG_EDGE_SELECT_SHIFT               9
#define BCHP_MISC_SEC_CO_SA_CONFIG_EDGE_SELECT_RISE_EDGE           0
#define BCHP_MISC_SEC_CO_SA_CONFIG_EDGE_SELECT_FALL_EDGE           1
#define BCHP_MISC_SEC_CO_SA_CONFIG_EDGE_SELECT_BOTH_EDGES          2
#define BCHP_MISC_SEC_CO_SA_CONFIG_EDGE_SELECT_NOT_DEFINED         3

/* MISC :: SEC_CO_SA_CONFIG :: SA_CH0_EN [08:08] */
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH0_EN_MASK                  0x00000100
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH0_EN_SHIFT                 8
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH0_EN_ON                    1
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH0_EN_OFF                   0

/* MISC :: SEC_CO_SA_CONFIG :: SA_CH1_EN [07:07] */
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH1_EN_MASK                  0x00000080
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH1_EN_SHIFT                 7
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH1_EN_ON                    1
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH1_EN_OFF                   0

/* MISC :: SEC_CO_SA_CONFIG :: SA_CH2_EN [06:06] */
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH2_EN_MASK                  0x00000040
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH2_EN_SHIFT                 6
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH2_EN_ON                    1
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH2_EN_OFF                   0

/* MISC :: SEC_CO_SA_CONFIG :: SA_CH0_CLEAR [05:05] */
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH0_CLEAR_MASK               0x00000020
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH0_CLEAR_SHIFT              5
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH0_CLEAR_ON                 1
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH0_CLEAR_OFF                0

/* MISC :: SEC_CO_SA_CONFIG :: SA_CH1_CLEAR [04:04] */
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH1_CLEAR_MASK               0x00000010
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH1_CLEAR_SHIFT              4
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH1_CLEAR_ON                 1
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH1_CLEAR_OFF                0

/* MISC :: SEC_CO_SA_CONFIG :: SA_CH2_CLEAR [03:03] */
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH2_CLEAR_MASK               0x00000008
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH2_CLEAR_SHIFT              3
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH2_CLEAR_ON                 1
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_CH2_CLEAR_OFF                0

/* MISC :: SEC_CO_SA_CONFIG :: SA_PROBE_RATE [02:00] */
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_MASK              0x00000007
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_SHIFT             0
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_ZERO              0
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_PER_WINDOW        1
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_PER_2WINDOWS      2
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_PER_3WINDOWS      3
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_PER_4WINDOWS      4
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_PER_5WINDOWS      5
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_PER_6WINDOWS      6
#define BCHP_MISC_SEC_CO_SA_CONFIG_SA_PROBE_RATE_PER_7WINDOWS      7

/***************************************************************************
 *SYNC_DELAY_REG - DELAY Register for Digital Sync
 ***************************************************************************/
/* MISC :: SYNC_DELAY_REG :: reserved0 [31:22] */
#define BCHP_MISC_SYNC_DELAY_REG_reserved0_MASK                    0xffc00000
#define BCHP_MISC_SYNC_DELAY_REG_reserved0_SHIFT                   22

/* MISC :: SYNC_DELAY_REG :: EXT_SYNC1 [21:20] */
#define BCHP_MISC_SYNC_DELAY_REG_EXT_SYNC1_MASK                    0x00300000
#define BCHP_MISC_SYNC_DELAY_REG_EXT_SYNC1_SHIFT                   20
#define BCHP_MISC_SYNC_DELAY_REG_EXT_SYNC1_PRIM                    0
#define BCHP_MISC_SYNC_DELAY_REG_EXT_SYNC1_SEC                     1

/* MISC :: SYNC_DELAY_REG :: EXT_SYNC0 [19:18] */
#define BCHP_MISC_SYNC_DELAY_REG_EXT_SYNC0_MASK                    0x000c0000
#define BCHP_MISC_SYNC_DELAY_REG_EXT_SYNC0_SHIFT                   18
#define BCHP_MISC_SYNC_DELAY_REG_EXT_SYNC0_PRIM                    0
#define BCHP_MISC_SYNC_DELAY_REG_EXT_SYNC0_SEC                     1

/* MISC :: SYNC_DELAY_REG :: reserved1 [17:12] */
#define BCHP_MISC_SYNC_DELAY_REG_reserved1_MASK                    0x0003f000
#define BCHP_MISC_SYNC_DELAY_REG_reserved1_SHIFT                   12

/* MISC :: SYNC_DELAY_REG :: DIG_SEC_SYNC_1 [11:09] */
#define BCHP_MISC_SYNC_DELAY_REG_DIG_SEC_SYNC_1_MASK               0x00000e00
#define BCHP_MISC_SYNC_DELAY_REG_DIG_SEC_SYNC_1_SHIFT              9

/* MISC :: SYNC_DELAY_REG :: DIG_SEC_SYNC_0 [08:06] */
#define BCHP_MISC_SYNC_DELAY_REG_DIG_SEC_SYNC_0_MASK               0x000001c0
#define BCHP_MISC_SYNC_DELAY_REG_DIG_SEC_SYNC_0_SHIFT              6

/* MISC :: SYNC_DELAY_REG :: DIG_PRIM_SYNC_1 [05:03] */
#define BCHP_MISC_SYNC_DELAY_REG_DIG_PRIM_SYNC_1_MASK              0x00000038
#define BCHP_MISC_SYNC_DELAY_REG_DIG_PRIM_SYNC_1_SHIFT             3

/* MISC :: SYNC_DELAY_REG :: DIG_PRIM_SYNC_0 [02:00] */
#define BCHP_MISC_SYNC_DELAY_REG_DIG_PRIM_SYNC_0_MASK              0x00000007
#define BCHP_MISC_SYNC_DELAY_REG_DIG_PRIM_SYNC_0_SHIFT             0

/***************************************************************************
 *DVI_SA_CONFIG - DVI SA Configuration Register
 ***************************************************************************/
/* MISC :: DVI_SA_CONFIG :: reserved0 [31:07] */
#define BCHP_MISC_DVI_SA_CONFIG_reserved0_MASK                     0xffffff80
#define BCHP_MISC_DVI_SA_CONFIG_reserved0_SHIFT                    7

/* MISC :: DVI_SA_CONFIG :: EDGE_SELECT [06:05] */
#define BCHP_MISC_DVI_SA_CONFIG_EDGE_SELECT_MASK                   0x00000060
#define BCHP_MISC_DVI_SA_CONFIG_EDGE_SELECT_SHIFT                  5
#define BCHP_MISC_DVI_SA_CONFIG_EDGE_SELECT_RISE_EDGE              0
#define BCHP_MISC_DVI_SA_CONFIG_EDGE_SELECT_FALL_EDGE              1
#define BCHP_MISC_DVI_SA_CONFIG_EDGE_SELECT_BOTH_EDGES             2
#define BCHP_MISC_DVI_SA_CONFIG_EDGE_SELECT_NOT_DEFINED            3

/* MISC :: DVI_SA_CONFIG :: SA_EN [04:04] */
#define BCHP_MISC_DVI_SA_CONFIG_SA_EN_MASK                         0x00000010
#define BCHP_MISC_DVI_SA_CONFIG_SA_EN_SHIFT                        4
#define BCHP_MISC_DVI_SA_CONFIG_SA_EN_ON                           1
#define BCHP_MISC_DVI_SA_CONFIG_SA_EN_OFF                          0

/* MISC :: DVI_SA_CONFIG :: SA_CLEAR [03:03] */
#define BCHP_MISC_DVI_SA_CONFIG_SA_CLEAR_MASK                      0x00000008
#define BCHP_MISC_DVI_SA_CONFIG_SA_CLEAR_SHIFT                     3
#define BCHP_MISC_DVI_SA_CONFIG_SA_CLEAR_ON                        1
#define BCHP_MISC_DVI_SA_CONFIG_SA_CLEAR_OFF                       0

/* MISC :: DVI_SA_CONFIG :: SA_PROBE_RATE [02:00] */
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_MASK                 0x00000007
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_SHIFT                0
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_ZERO                 0
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_PER_WINDOW           1
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_PER_2WINDOWS         2
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_PER_3WINDOWS         3
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_PER_4WINDOWS         4
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_PER_5WINDOWS         5
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_PER_6WINDOWS         6
#define BCHP_MISC_DVI_SA_CONFIG_SA_PROBE_RATE_PER_7WINDOWS         7

/***************************************************************************
 *DVI_SA_STATUS - DVI SA Status Register
 ***************************************************************************/
/* MISC :: DVI_SA_STATUS :: SA_DATA [31:00] */
#define BCHP_MISC_DVI_SA_STATUS_SA_DATA_MASK                       0xffffffff
#define BCHP_MISC_DVI_SA_STATUS_SA_DATA_SHIFT                      0

/***************************************************************************
 *PRIM_MASTER_SEL - Master Select for Primary VEC path
 ***************************************************************************/
/* MISC :: PRIM_MASTER_SEL :: reserved0 [31:03] */
#define BCHP_MISC_PRIM_MASTER_SEL_reserved0_MASK                   0xfffffff8
#define BCHP_MISC_PRIM_MASTER_SEL_reserved0_SHIFT                  3

/* MISC :: PRIM_MASTER_SEL :: SELECT [02:00] */
#define BCHP_MISC_PRIM_MASTER_SEL_SELECT_MASK                      0x00000007
#define BCHP_MISC_PRIM_MASTER_SEL_SELECT_SHIFT                     0
#define BCHP_MISC_PRIM_MASTER_SEL_SELECT_SEC                       1
#define BCHP_MISC_PRIM_MASTER_SEL_SELECT_DVI                       3
#define BCHP_MISC_PRIM_MASTER_SEL_SELECT_Unused                    4

/***************************************************************************
 *SEC_MASTER_SEL - Master Select for Secondary VEC path
 ***************************************************************************/
/* MISC :: SEC_MASTER_SEL :: reserved0 [31:03] */
#define BCHP_MISC_SEC_MASTER_SEL_reserved0_MASK                    0xfffffff8
#define BCHP_MISC_SEC_MASTER_SEL_reserved0_SHIFT                   3

/* MISC :: SEC_MASTER_SEL :: SELECT [02:00] */
#define BCHP_MISC_SEC_MASTER_SEL_SELECT_MASK                       0x00000007
#define BCHP_MISC_SEC_MASTER_SEL_SELECT_SHIFT                      0
#define BCHP_MISC_SEC_MASTER_SEL_SELECT_PRIM                       0
#define BCHP_MISC_SEC_MASTER_SEL_SELECT_DVI                        3
#define BCHP_MISC_SEC_MASTER_SEL_SELECT_Unused                     4

/***************************************************************************
 *DVI_MASTER_SEL - Master Select for DVI VEC path
 ***************************************************************************/
/* MISC :: DVI_MASTER_SEL :: reserved0 [31:04] */
#define BCHP_MISC_DVI_MASTER_SEL_reserved0_MASK                    0xfffffff0
#define BCHP_MISC_DVI_MASTER_SEL_reserved0_SHIFT                   4

/* MISC :: DVI_MASTER_SEL :: FREERUN [03:03] */
#define BCHP_MISC_DVI_MASTER_SEL_FREERUN_MASK                      0x00000008
#define BCHP_MISC_DVI_MASTER_SEL_FREERUN_SHIFT                     3

/* MISC :: DVI_MASTER_SEL :: SELECT [02:00] */
#define BCHP_MISC_DVI_MASTER_SEL_SELECT_MASK                       0x00000007
#define BCHP_MISC_DVI_MASTER_SEL_SELECT_SHIFT                      0
#define BCHP_MISC_DVI_MASTER_SEL_SELECT_PRIM                       0
#define BCHP_MISC_DVI_MASTER_SEL_SELECT_SEC                        1
#define BCHP_MISC_DVI_MASTER_SEL_SELECT_Unused                     4

/***************************************************************************
 *DAC_BG_CTRL_REG - HEXDAC Bandgap Control Register
 ***************************************************************************/
/* MISC :: DAC_BG_CTRL_REG :: reserved0 [31:16] */
#define BCHP_MISC_DAC_BG_CTRL_REG_reserved0_MASK                   0xffff0000
#define BCHP_MISC_DAC_BG_CTRL_REG_reserved0_SHIFT                  16

/* MISC :: DAC_BG_CTRL_REG :: UNUSED [15:14] */
#define BCHP_MISC_DAC_BG_CTRL_REG_UNUSED_MASK                      0x0000c000
#define BCHP_MISC_DAC_BG_CTRL_REG_UNUSED_SHIFT                     14

/* MISC :: DAC_BG_CTRL_REG :: PWRDN_CORE [13:13] */
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_CORE_MASK                  0x00002000
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_CORE_SHIFT                 13
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_CORE_PWRUP                 0
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_CORE_PWRDN                 1

/* MISC :: DAC_BG_CTRL_REG :: CORE_ADJ [12:10] */
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_MASK                    0x00001c00
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_SHIFT                   10
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_ZERO                    0
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_ONE                     1
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_TWO                     2
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_THREE                   3
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_FOUR                    4
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_FIVE                    5
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_SIX                     6
#define BCHP_MISC_DAC_BG_CTRL_REG_CORE_ADJ_SEVEN                   7

/* MISC :: DAC_BG_CTRL_REG :: AUX_ADJ [09:08] */
#define BCHP_MISC_DAC_BG_CTRL_REG_AUX_ADJ_MASK                     0x00000300
#define BCHP_MISC_DAC_BG_CTRL_REG_AUX_ADJ_SHIFT                    8
#define BCHP_MISC_DAC_BG_CTRL_REG_AUX_ADJ_ZERO                     0
#define BCHP_MISC_DAC_BG_CTRL_REG_AUX_ADJ_ONE                      1
#define BCHP_MISC_DAC_BG_CTRL_REG_AUX_ADJ_TWO                      2
#define BCHP_MISC_DAC_BG_CTRL_REG_AUX_ADJ_THREE                    3

/* MISC :: DAC_BG_CTRL_REG :: DBG_EN_AUX [07:07] */
#define BCHP_MISC_DAC_BG_CTRL_REG_DBG_EN_AUX_MASK                  0x00000080
#define BCHP_MISC_DAC_BG_CTRL_REG_DBG_EN_AUX_SHIFT                 7
#define BCHP_MISC_DAC_BG_CTRL_REG_DBG_EN_AUX_ZERO                  0
#define BCHP_MISC_DAC_BG_CTRL_REG_DBG_EN_AUX_ONE                   1

/* MISC :: DAC_BG_CTRL_REG :: PWRDN_AUX [06:06] */
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_AUX_MASK                   0x00000040
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_AUX_SHIFT                  6
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_AUX_POWER_DOWN             1
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_AUX_POWER_UP               0

/* MISC :: DAC_BG_CTRL_REG :: IREF_ADJ [05:01] */
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_MASK                    0x0000003e
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_SHIFT                   1
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_ZERO                    0
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_ONE                     1
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWO                     2
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_THREE                   3
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_FOUR                    4
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_FIVE                    5
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_SIX                     6
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_SEVEN                   7
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_EIGHT                   8
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_NINE                    9
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TEN                     10
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_ELEVEN                  11
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWELVE                  12
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_THIRTEEN                13
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_FOURTEEN                14
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_FIFTEEN                 15
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_SIXTEEN                 16
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_SEVENTEEN               17
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_EIGHTEEN                18
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_NINETEEN                19
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY                  20
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY_ONE              21
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY_TWO              22
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY_THREE            23
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY_FOUR             24
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY_FIVE             25
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY_SIX              26
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY_SEVEN            27
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY_EIGHT            28
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_TWENTY_NINE             29
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_THIRTY                  30
#define BCHP_MISC_DAC_BG_CTRL_REG_IREF_ADJ_THIRTY_ONE              31

/* MISC :: DAC_BG_CTRL_REG :: PWRDN_REFAMP [00:00] */
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_REFAMP_MASK                0x00000001
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_REFAMP_SHIFT               0
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_REFAMP_POWER_DOWN          1
#define BCHP_MISC_DAC_BG_CTRL_REG_PWRDN_REFAMP_POWER_UP            0

/***************************************************************************
 *DAC1_CTRL_REG - HEXDAC1 Control Register
 ***************************************************************************/
/* MISC :: DAC1_CTRL_REG :: reserved0 [31:16] */
#define BCHP_MISC_DAC1_CTRL_REG_reserved0_MASK                     0xffff0000
#define BCHP_MISC_DAC1_CTRL_REG_reserved0_SHIFT                    16

/* MISC :: DAC1_CTRL_REG :: PWRDN_CORE [15:15] */
#define BCHP_MISC_DAC1_CTRL_REG_PWRDN_CORE_MASK                    0x00008000
#define BCHP_MISC_DAC1_CTRL_REG_PWRDN_CORE_SHIFT                   15
#define BCHP_MISC_DAC1_CTRL_REG_PWRDN_CORE_PWRUP                   0
#define BCHP_MISC_DAC1_CTRL_REG_PWRDN_CORE_PWRDN                   1

/* MISC :: DAC1_CTRL_REG :: CLK_INV [14:14] */
#define BCHP_MISC_DAC1_CTRL_REG_CLK_INV_MASK                       0x00004000
#define BCHP_MISC_DAC1_CTRL_REG_CLK_INV_SHIFT                      14
#define BCHP_MISC_DAC1_CTRL_REG_CLK_INV_NORM                       0
#define BCHP_MISC_DAC1_CTRL_REG_CLK_INV_ON                         1

/* MISC :: DAC1_CTRL_REG :: TC_OBB [13:13] */
#define BCHP_MISC_DAC1_CTRL_REG_TC_OBB_MASK                        0x00002000
#define BCHP_MISC_DAC1_CTRL_REG_TC_OBB_SHIFT                       13
#define BCHP_MISC_DAC1_CTRL_REG_TC_OBB_OFFSET                      0
#define BCHP_MISC_DAC1_CTRL_REG_TC_OBB_COMP                        1

/* MISC :: DAC1_CTRL_REG :: DC_DATA [12:01] */
#define BCHP_MISC_DAC1_CTRL_REG_DC_DATA_MASK                       0x00001ffe
#define BCHP_MISC_DAC1_CTRL_REG_DC_DATA_SHIFT                      1

/* MISC :: DAC1_CTRL_REG :: DCENBL [00:00] */
#define BCHP_MISC_DAC1_CTRL_REG_DCENBL_MASK                        0x00000001
#define BCHP_MISC_DAC1_CTRL_REG_DCENBL_SHIFT                       0
#define BCHP_MISC_DAC1_CTRL_REG_DCENBL_NORM                        0
#define BCHP_MISC_DAC1_CTRL_REG_DCENBL_ON                          1

/***************************************************************************
 *DAC2_CTRL_REG - HEXDAC2 Control Register
 ***************************************************************************/
/* MISC :: DAC2_CTRL_REG :: reserved0 [31:16] */
#define BCHP_MISC_DAC2_CTRL_REG_reserved0_MASK                     0xffff0000
#define BCHP_MISC_DAC2_CTRL_REG_reserved0_SHIFT                    16

/* MISC :: DAC2_CTRL_REG :: PWRDN_CORE [15:15] */
#define BCHP_MISC_DAC2_CTRL_REG_PWRDN_CORE_MASK                    0x00008000
#define BCHP_MISC_DAC2_CTRL_REG_PWRDN_CORE_SHIFT                   15
#define BCHP_MISC_DAC2_CTRL_REG_PWRDN_CORE_PWRUP                   0
#define BCHP_MISC_DAC2_CTRL_REG_PWRDN_CORE_PWRDN                   1

/* MISC :: DAC2_CTRL_REG :: CLK_INV [14:14] */
#define BCHP_MISC_DAC2_CTRL_REG_CLK_INV_MASK                       0x00004000
#define BCHP_MISC_DAC2_CTRL_REG_CLK_INV_SHIFT                      14
#define BCHP_MISC_DAC2_CTRL_REG_CLK_INV_NORM                       0
#define BCHP_MISC_DAC2_CTRL_REG_CLK_INV_ON                         1

/* MISC :: DAC2_CTRL_REG :: TC_OBB [13:13] */
#define BCHP_MISC_DAC2_CTRL_REG_TC_OBB_MASK                        0x00002000
#define BCHP_MISC_DAC2_CTRL_REG_TC_OBB_SHIFT                       13
#define BCHP_MISC_DAC2_CTRL_REG_TC_OBB_OFFSET                      0
#define BCHP_MISC_DAC2_CTRL_REG_TC_OBB_COMP                        1

/* MISC :: DAC2_CTRL_REG :: DC_DATA [12:01] */
#define BCHP_MISC_DAC2_CTRL_REG_DC_DATA_MASK                       0x00001ffe
#define BCHP_MISC_DAC2_CTRL_REG_DC_DATA_SHIFT                      1

/* MISC :: DAC2_CTRL_REG :: DCENBL [00:00] */
#define BCHP_MISC_DAC2_CTRL_REG_DCENBL_MASK                        0x00000001
#define BCHP_MISC_DAC2_CTRL_REG_DCENBL_SHIFT                       0
#define BCHP_MISC_DAC2_CTRL_REG_DCENBL_NORM                        0
#define BCHP_MISC_DAC2_CTRL_REG_DCENBL_ON                          1

/***************************************************************************
 *DAC3_CTRL_REG - HEXDAC3 Control Register
 ***************************************************************************/
/* MISC :: DAC3_CTRL_REG :: reserved0 [31:16] */
#define BCHP_MISC_DAC3_CTRL_REG_reserved0_MASK                     0xffff0000
#define BCHP_MISC_DAC3_CTRL_REG_reserved0_SHIFT                    16

/* MISC :: DAC3_CTRL_REG :: PWRDN_CORE [15:15] */
#define BCHP_MISC_DAC3_CTRL_REG_PWRDN_CORE_MASK                    0x00008000
#define BCHP_MISC_DAC3_CTRL_REG_PWRDN_CORE_SHIFT                   15
#define BCHP_MISC_DAC3_CTRL_REG_PWRDN_CORE_PWRUP                   0
#define BCHP_MISC_DAC3_CTRL_REG_PWRDN_CORE_PWRDN                   1

/* MISC :: DAC3_CTRL_REG :: CLK_INV [14:14] */
#define BCHP_MISC_DAC3_CTRL_REG_CLK_INV_MASK                       0x00004000
#define BCHP_MISC_DAC3_CTRL_REG_CLK_INV_SHIFT                      14
#define BCHP_MISC_DAC3_CTRL_REG_CLK_INV_NORM                       0
#define BCHP_MISC_DAC3_CTRL_REG_CLK_INV_ON                         1

/* MISC :: DAC3_CTRL_REG :: TC_OBB [13:13] */
#define BCHP_MISC_DAC3_CTRL_REG_TC_OBB_MASK                        0x00002000
#define BCHP_MISC_DAC3_CTRL_REG_TC_OBB_SHIFT                       13
#define BCHP_MISC_DAC3_CTRL_REG_TC_OBB_OFFSET                      0
#define BCHP_MISC_DAC3_CTRL_REG_TC_OBB_COMP                        1

/* MISC :: DAC3_CTRL_REG :: DC_DATA [12:01] */
#define BCHP_MISC_DAC3_CTRL_REG_DC_DATA_MASK                       0x00001ffe
#define BCHP_MISC_DAC3_CTRL_REG_DC_DATA_SHIFT                      1

/* MISC :: DAC3_CTRL_REG :: DCENBL [00:00] */
#define BCHP_MISC_DAC3_CTRL_REG_DCENBL_MASK                        0x00000001
#define BCHP_MISC_DAC3_CTRL_REG_DCENBL_SHIFT                       0
#define BCHP_MISC_DAC3_CTRL_REG_DCENBL_NORM                        0
#define BCHP_MISC_DAC3_CTRL_REG_DCENBL_ON                          1

/***************************************************************************
 *DAC4_CTRL_REG - HEXDAC4 Control Register
 ***************************************************************************/
/* MISC :: DAC4_CTRL_REG :: reserved0 [31:16] */
#define BCHP_MISC_DAC4_CTRL_REG_reserved0_MASK                     0xffff0000
#define BCHP_MISC_DAC4_CTRL_REG_reserved0_SHIFT                    16

/* MISC :: DAC4_CTRL_REG :: PWRDN_CORE [15:15] */
#define BCHP_MISC_DAC4_CTRL_REG_PWRDN_CORE_MASK                    0x00008000
#define BCHP_MISC_DAC4_CTRL_REG_PWRDN_CORE_SHIFT                   15
#define BCHP_MISC_DAC4_CTRL_REG_PWRDN_CORE_PWRUP                   0
#define BCHP_MISC_DAC4_CTRL_REG_PWRDN_CORE_PWRDN                   1

/* MISC :: DAC4_CTRL_REG :: CLK_INV [14:14] */
#define BCHP_MISC_DAC4_CTRL_REG_CLK_INV_MASK                       0x00004000
#define BCHP_MISC_DAC4_CTRL_REG_CLK_INV_SHIFT                      14
#define BCHP_MISC_DAC4_CTRL_REG_CLK_INV_NORM                       0
#define BCHP_MISC_DAC4_CTRL_REG_CLK_INV_ON                         1

/* MISC :: DAC4_CTRL_REG :: TC_OBB [13:13] */
#define BCHP_MISC_DAC4_CTRL_REG_TC_OBB_MASK                        0x00002000
#define BCHP_MISC_DAC4_CTRL_REG_TC_OBB_SHIFT                       13
#define BCHP_MISC_DAC4_CTRL_REG_TC_OBB_OFFSET                      0
#define BCHP_MISC_DAC4_CTRL_REG_TC_OBB_COMP                        1

/* MISC :: DAC4_CTRL_REG :: DC_DATA [12:01] */
#define BCHP_MISC_DAC4_CTRL_REG_DC_DATA_MASK                       0x00001ffe
#define BCHP_MISC_DAC4_CTRL_REG_DC_DATA_SHIFT                      1

/* MISC :: DAC4_CTRL_REG :: DCENBL [00:00] */
#define BCHP_MISC_DAC4_CTRL_REG_DCENBL_MASK                        0x00000001
#define BCHP_MISC_DAC4_CTRL_REG_DCENBL_SHIFT                       0
#define BCHP_MISC_DAC4_CTRL_REG_DCENBL_NORM                        0
#define BCHP_MISC_DAC4_CTRL_REG_DCENBL_ON                          1

/***************************************************************************
 *DAC5_CTRL_REG - HEXDAC5 Control Register
 ***************************************************************************/
/* MISC :: DAC5_CTRL_REG :: reserved0 [31:16] */
#define BCHP_MISC_DAC5_CTRL_REG_reserved0_MASK                     0xffff0000
#define BCHP_MISC_DAC5_CTRL_REG_reserved0_SHIFT                    16

/* MISC :: DAC5_CTRL_REG :: PWRDN_CORE [15:15] */
#define BCHP_MISC_DAC5_CTRL_REG_PWRDN_CORE_MASK                    0x00008000
#define BCHP_MISC_DAC5_CTRL_REG_PWRDN_CORE_SHIFT                   15
#define BCHP_MISC_DAC5_CTRL_REG_PWRDN_CORE_PWRUP                   0
#define BCHP_MISC_DAC5_CTRL_REG_PWRDN_CORE_PWRDN                   1

/* MISC :: DAC5_CTRL_REG :: CLK_INV [14:14] */
#define BCHP_MISC_DAC5_CTRL_REG_CLK_INV_MASK                       0x00004000
#define BCHP_MISC_DAC5_CTRL_REG_CLK_INV_SHIFT                      14
#define BCHP_MISC_DAC5_CTRL_REG_CLK_INV_NORM                       0
#define BCHP_MISC_DAC5_CTRL_REG_CLK_INV_ON                         1

/* MISC :: DAC5_CTRL_REG :: TC_OBB [13:13] */
#define BCHP_MISC_DAC5_CTRL_REG_TC_OBB_MASK                        0x00002000
#define BCHP_MISC_DAC5_CTRL_REG_TC_OBB_SHIFT                       13
#define BCHP_MISC_DAC5_CTRL_REG_TC_OBB_OFFSET                      0
#define BCHP_MISC_DAC5_CTRL_REG_TC_OBB_COMP                        1

/* MISC :: DAC5_CTRL_REG :: DC_DATA [12:01] */
#define BCHP_MISC_DAC5_CTRL_REG_DC_DATA_MASK                       0x00001ffe
#define BCHP_MISC_DAC5_CTRL_REG_DC_DATA_SHIFT                      1

/* MISC :: DAC5_CTRL_REG :: DCENBL [00:00] */
#define BCHP_MISC_DAC5_CTRL_REG_DCENBL_MASK                        0x00000001
#define BCHP_MISC_DAC5_CTRL_REG_DCENBL_SHIFT                       0
#define BCHP_MISC_DAC5_CTRL_REG_DCENBL_NORM                        0
#define BCHP_MISC_DAC5_CTRL_REG_DCENBL_ON                          1

/***************************************************************************
 *DAC6_CTRL_REG - HEXDAC6 Control Register
 ***************************************************************************/
/* MISC :: DAC6_CTRL_REG :: reserved0 [31:16] */
#define BCHP_MISC_DAC6_CTRL_REG_reserved0_MASK                     0xffff0000
#define BCHP_MISC_DAC6_CTRL_REG_reserved0_SHIFT                    16

/* MISC :: DAC6_CTRL_REG :: PWRDN_CORE [15:15] */
#define BCHP_MISC_DAC6_CTRL_REG_PWRDN_CORE_MASK                    0x00008000
#define BCHP_MISC_DAC6_CTRL_REG_PWRDN_CORE_SHIFT                   15
#define BCHP_MISC_DAC6_CTRL_REG_PWRDN_CORE_PWRUP                   0
#define BCHP_MISC_DAC6_CTRL_REG_PWRDN_CORE_PWRDN                   1

/* MISC :: DAC6_CTRL_REG :: CLK_INV [14:14] */
#define BCHP_MISC_DAC6_CTRL_REG_CLK_INV_MASK                       0x00004000
#define BCHP_MISC_DAC6_CTRL_REG_CLK_INV_SHIFT                      14
#define BCHP_MISC_DAC6_CTRL_REG_CLK_INV_NORM                       0
#define BCHP_MISC_DAC6_CTRL_REG_CLK_INV_ON                         1

/* MISC :: DAC6_CTRL_REG :: TC_OBB [13:13] */
#define BCHP_MISC_DAC6_CTRL_REG_TC_OBB_MASK                        0x00002000
#define BCHP_MISC_DAC6_CTRL_REG_TC_OBB_SHIFT                       13
#define BCHP_MISC_DAC6_CTRL_REG_TC_OBB_OFFSET                      0
#define BCHP_MISC_DAC6_CTRL_REG_TC_OBB_COMP                        1

/* MISC :: DAC6_CTRL_REG :: DC_DATA [12:01] */
#define BCHP_MISC_DAC6_CTRL_REG_DC_DATA_MASK                       0x00001ffe
#define BCHP_MISC_DAC6_CTRL_REG_DC_DATA_SHIFT                      1

/* MISC :: DAC6_CTRL_REG :: DCENBL [00:00] */
#define BCHP_MISC_DAC6_CTRL_REG_DCENBL_MASK                        0x00000001
#define BCHP_MISC_DAC6_CTRL_REG_DCENBL_SHIFT                       0
#define BCHP_MISC_DAC6_CTRL_REG_DCENBL_NORM                        0
#define BCHP_MISC_DAC6_CTRL_REG_DCENBL_ON                          1

/***************************************************************************
 *DVI_DITHERING - DVI Dithering Register
 ***************************************************************************/
/* MISC :: DVI_DITHERING :: reserved0 [31:05] */
#define BCHP_MISC_DVI_DITHERING_reserved0_MASK                     0xffffffe0
#define BCHP_MISC_DVI_DITHERING_reserved0_SHIFT                    5

/* MISC :: DVI_DITHERING :: LFSR_RESET [04:03] */
#define BCHP_MISC_DVI_DITHERING_LFSR_RESET_MASK                    0x00000018
#define BCHP_MISC_DVI_DITHERING_LFSR_RESET_SHIFT                   3
#define BCHP_MISC_DVI_DITHERING_LFSR_RESET_NO_RESET                0
#define BCHP_MISC_DVI_DITHERING_LFSR_RESET_EVERY_SOP               1
#define BCHP_MISC_DVI_DITHERING_LFSR_RESET_EVERY_OTHER_SOP         2

/* MISC :: DVI_DITHERING :: DITHER_BITS [02:00] */
#define BCHP_MISC_DVI_DITHERING_DITHER_BITS_MASK                   0x00000007
#define BCHP_MISC_DVI_DITHERING_DITHER_BITS_SHIFT                  0

/***************************************************************************
 *PRIM_CH0_SA_STATUS - PRIM Channel 0 SA Status Register
 ***************************************************************************/
/* MISC :: PRIM_CH0_SA_STATUS :: STATUS [31:00] */
#define BCHP_MISC_PRIM_CH0_SA_STATUS_STATUS_MASK                   0xffffffff
#define BCHP_MISC_PRIM_CH0_SA_STATUS_STATUS_SHIFT                  0

/***************************************************************************
 *PRIM_CH1_SA_STATUS - PRIM Channel 1 SA Status Register
 ***************************************************************************/
/* MISC :: PRIM_CH1_SA_STATUS :: STATUS [31:00] */
#define BCHP_MISC_PRIM_CH1_SA_STATUS_STATUS_MASK                   0xffffffff
#define BCHP_MISC_PRIM_CH1_SA_STATUS_STATUS_SHIFT                  0

/***************************************************************************
 *PRIM_CH2_SA_STATUS - PRIM Channel 2 SA Status Register
 ***************************************************************************/
/* MISC :: PRIM_CH2_SA_STATUS :: STATUS [31:00] */
#define BCHP_MISC_PRIM_CH2_SA_STATUS_STATUS_MASK                   0xffffffff
#define BCHP_MISC_PRIM_CH2_SA_STATUS_STATUS_SHIFT                  0

/***************************************************************************
 *PRIM_SA_CONFIG - PRIM SA Config Register
 ***************************************************************************/
/* MISC :: PRIM_SA_CONFIG :: reserved0 [31:11] */
#define BCHP_MISC_PRIM_SA_CONFIG_reserved0_MASK                    0xfffff800
#define BCHP_MISC_PRIM_SA_CONFIG_reserved0_SHIFT                   11

/* MISC :: PRIM_SA_CONFIG :: EDGE_SELECT [10:09] */
#define BCHP_MISC_PRIM_SA_CONFIG_EDGE_SELECT_MASK                  0x00000600
#define BCHP_MISC_PRIM_SA_CONFIG_EDGE_SELECT_SHIFT                 9
#define BCHP_MISC_PRIM_SA_CONFIG_EDGE_SELECT_RISE_EDGE             0
#define BCHP_MISC_PRIM_SA_CONFIG_EDGE_SELECT_FALL_EDGE             1
#define BCHP_MISC_PRIM_SA_CONFIG_EDGE_SELECT_BOTH_EDGES            2
#define BCHP_MISC_PRIM_SA_CONFIG_EDGE_SELECT_NOT_DEFINED           3

/* MISC :: PRIM_SA_CONFIG :: SA_CH0_EN [08:08] */
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH0_EN_MASK                    0x00000100
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH0_EN_SHIFT                   8
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH0_EN_ON                      1
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH0_EN_OFF                     0

/* MISC :: PRIM_SA_CONFIG :: SA_CH1_EN [07:07] */
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH1_EN_MASK                    0x00000080
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH1_EN_SHIFT                   7
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH1_EN_ON                      1
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH1_EN_OFF                     0

/* MISC :: PRIM_SA_CONFIG :: SA_CH2_EN [06:06] */
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH2_EN_MASK                    0x00000040
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH2_EN_SHIFT                   6
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH2_EN_ON                      1
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH2_EN_OFF                     0

/* MISC :: PRIM_SA_CONFIG :: SA_CH0_CLEAR [05:05] */
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH0_CLEAR_MASK                 0x00000020
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH0_CLEAR_SHIFT                5
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH0_CLEAR_ON                   1
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH0_CLEAR_OFF                  0

/* MISC :: PRIM_SA_CONFIG :: SA_CH1_CLEAR [04:04] */
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH1_CLEAR_MASK                 0x00000010
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH1_CLEAR_SHIFT                4
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH1_CLEAR_ON                   1
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH1_CLEAR_OFF                  0

/* MISC :: PRIM_SA_CONFIG :: SA_CH2_CLEAR [03:03] */
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH2_CLEAR_MASK                 0x00000008
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH2_CLEAR_SHIFT                3
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH2_CLEAR_ON                   1
#define BCHP_MISC_PRIM_SA_CONFIG_SA_CH2_CLEAR_OFF                  0

/* MISC :: PRIM_SA_CONFIG :: SA_PROBE_RATE [02:00] */
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_MASK                0x00000007
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_SHIFT               0
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_ZERO                0
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_PER_WINDOW          1
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_PER_2WINDOWS        2
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_PER_3WINDOWS        3
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_PER_4WINDOWS        4
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_PER_5WINDOWS        5
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_PER_6WINDOWS        6
#define BCHP_MISC_PRIM_SA_CONFIG_SA_PROBE_RATE_PER_7WINDOWS        7

#endif /* #ifndef BCHP_MISC_H__ */

/* End of File */
